# -*- coding: utf-8 -*-
import json
import sys
sys.path.insert(0, '/workspace')
from translate_ko2 import TRANS2

ZH_PATH = '/workspace/src/ForkPlus/Languages/zh-Hans.json'
KO_PATH = '/workspace/src/ForkPlus/Languages/ko-KR.json'

TRANS = {
    "\nResponse:\n": "\n응답:\n",
    "  Avg: {0:0.000}s": "  평균: {0:0.000}s",
    "  Measurements (s): {0:0.000}*, {1}, {2:0.000}*": "  측정값(초): {0:0.000}*, {1}, {2:0.000}*",
    " (applied {0}/{1} commits)": " ({0}/{1}개 커밋 적용됨)",
    " Amending '{0}'.": " '{0}' 수정 중.",
    " Avg test time: {0:0.000}s": " 평균 테스트 시간: {0:0.000}s",
    " Score = 10 / {0:0.000} = {1:0.0}": " 점수 = 10 / {0:0.000} = {1:0.0}",
    " Title:": " 제목:",
    " Total time: {0:0.000}s": " 총 시간: {0:0.000}s",
    "# Apply stashed changes:": "# 스태시 변경사항 적용:",
    "# Apply stashed changes:\n": "# 스태시 변경사항 적용:\n",
    "# Move '{0}' to '{1}':\n": "# '{0}'을(를) '{1}'(으)로 이동:\n",
    "# Stash uncommitted changes:\n": "# 커밋되지 않은 변경사항 스태시:\n",
    "# Synchronize '{0}' with '{1}':\n": "# '{0}'과(와) '{1}' 동기화:\n",
    "# Update submodules:\n": "# 서브모듈 업데이트:\n",
    "' (rebased {0}/{1} commits)": "' ({0}/{1}개 커밋 리베이스됨)",
    "' and then continue.": "' 그리고 계속하세요.",
    "' good or bad?": "' 좋은가요, 나쁜가요?",
    "' into '": "' → '",
    "' → '": "' → '",
    "'. All conflicts fixed.": "'. 모든 충돌이 해결되었습니다.",
    "'. Fix {0} {1} and then continue.": "'. {0}개 {1}을(를) 해결한 후 계속하세요.",
    "'. Is '": "'. 인가요? ",
    "'. Mark current commit as good or bad and checkout another one": "'. 현재 커밋을 좋음/나쁨으로 표시하고 다른 것을 체크아웃하세요",
    "'{0}' already exists. Please choose another name.": "'{0}'이(가) 이미 존재합니다. 다른 이름을 선택하세요.",
    "'{0}' consists of a single commit. Using fast-forward": "'{0}'은(는) 단일 커밋으로 구성됩니다. 패스트포워드 사용",
    "'{0}' is already a git mm repository.": "'{0}'은(는) 이미 git mm 저장소입니다.",
    "'{0}' is already a git repository. Please select another folder.": "'{0}'은(는) 이미 Git 저장소입니다. 다른 폴더를 선택하세요.",
    "'{0}' is not in sync with '{1}'. You must checkout and sync '{0}' first.": "'{0}'이(가) '{1}'과(와) 동기화되지 않았습니다. 먼저 '{0}'을(를) 체크아웃하고 동기화해야 합니다.",
    "'{0}' rejected": "'{0}' 거부됨",
    "'{0}' {1} commits ahead '{2}'": "'{0}'이(가) '{2}'보다 {1}개 커밋 앞섬",
    "'{0}' {1} commits ahead, {2} commits behind '{3}'": "'{0}'이(가) {1}개 커밋 앞서고 '{3}'보다 {2}개 커밋 뒤처짐",
    "'{0}' {1} commits behind '{2}'": "'{0}'이(가) '{2}'보다 {1}개 커밋 뒤처짐",
    "(one pattern per line)": "(한 줄에 하나의 패턴)",
    "* double-click on folders to expand": "* 폴더를 더블클릭하여 펼치기",
    "*{0} files": "*{0}개 파일",
    "0 files match": "일치하는 파일 0개",
    "1 file matches": "일치하는 파일 1개",
    "1. Select or generate a new SSH key which will identify your computer\n2. Copy the public key content to the account section on the website of your git provider": "1. 컴퓨터를 식별할 새 SSH 키를 선택하거나 생성하세요\n2. 공개 키 내용을 Git 서비스 제공자 웹사이트의 계정 섹션에 복사하세요",
    ">{0} results": ">{0}개 결과",
    "A gitignore file specifies intentionally untracked files that Git should ignore. Files already tracked by Git will be untracked.": ".gitignore 파일은 Git이 무시할 의도적으로 추적되지 않은 파일을 지정합니다. 이미 Git이 추적 중인 파일은 추적이 해제됩니다.",
    "AI": "AI",
    "AI Code Review Completed": "AI 코드 리뷰 완료",
    "AI Code Review Failed": "AI 코드 리뷰 실패",
    "AI Enhancement": "AI 향상",
    "AI Model Configuration": "AI 모델 설정",
    "AI Review is not configured.": "AI 리뷰가 설정되지 않았습니다.",
    "AI commit message generation uses the AI Review settings tab.": "AI 커밋 메시지 생성은 AI 리뷰 설정 탭을 사용합니다.",
    "AI request is queued. Waiting {0} before checking again...": "AI 요청이 대기 중입니다. {0} 후 다시 확인합니다...",
    "AI request timed out or was canceled.": "AI 요청이 시간 초과되었거나 취소되었습니다.",
    "AI service is busy or queued. Retrying in {0}s ({1}/{2})...": "AI 서비스가 사용 중이거나 대기 중입니다. {0}초 후 재시도합니다 ({1}/{2})...",
    "AI service may be busy or timed out. Please retry later, reduce selected files, or increase retry/timeout in Preferences > AI Enhancement.": "AI 서비스가 사용 중이거나 시간 초과되었을 수 있습니다. 나중에 다시 시도하거나, 선택한 파일을 줄이거나, 환경설정 > AI 향상에서 재시도/시간 초과를 늘려주세요.",
    "AI service may be busy or timed out. Please retry later, reduce selected files, or increase retry/timeout in Preferences > AI Review.": "AI 서비스가 사용 중이거나 시간 초과되었을 수 있습니다. 나중에 다시 시도하거나, 선택한 파일을 줄이거나, 환경설정 > AI 리뷰에서 재시도/시간 초과를 늘려주세요.",
    "AI service returned an error: {0}": "AI 서비스에서 오류를 반환했습니다: {0}",
    "AI 开发": "AI 개발",
    "AI 正在生成代码...": "AI가 코드를 생성하는 중...",
    "AI 请求出错: {0}": "AI 요청 오류: {0}",
    "AI 请求失败: {0}": "AI 요청 실패: {0}",
    "AI-Assisted Development": "AI 보조 개발",
    "API Key:": "API 키:",
    "API Token:": "API 토큰:",
    "API token with scopes": "스코프가 있는 API 토큰",
    "AUTHOR": "작성자",
    "Abort AM": "AM 중단",
    "Abort cherry-pick": "체리픽 중단",
    "Abort merge": "병합 중단",
    "Abort rebase": "리베이스 중단",
    "Abort revert": "되돌리기 중단",
    "About ": "정보 ",
    "About Fork": "Fork 정보",
    "About ForkPlus": "ForkPlus 정보",
    "Access Token:": "액세스 토큰:",
    "Access regex groups using $1, $2 etc variables": "$1, $2 등의 변수를 사용하여 정규식 그룹에 액세스",
    "Access to Bitbucket repositories requires 'read:workspace:bitbucket' scope": "Bitbucket 저장소에 액세스하려면 'read:workspace:bitbucket' 스코프가 필요합니다",
    "Account": "계정",
    "Account:": "계정:",
    "Accounts...": "계정...",
    "Action": "동작",
    "Action:": "동작:",
    "Activate": "활성화",
    "Activating...": "활성화 중...",
    "Activity Manager": "활동 관리자",
    "Add .gitignore Template": ".gitignore 템플릿 추가",
    "Add .gitignore…": ".gitignore 추가…",
    "Add Account": "계정 추가",
    "Add Branch Custom Command": "브랜치 사용자 정의 명령 추가",
    "Add Branch Selector": "브랜치 선택기 추가",
    "Add Check Box": "체크박스 추가",
    "Add Commit Custom Command": "커밋 사용자 정의 명령 추가",
    "Add File Custom Command": "파일 사용자 정의 명령 추가",
    "Add New Remote": "새 리모트 추가",
    "Add New Rule": "새 규칙 추가",
    "Add New Submodule...": "새 서브모듈 추가...",
    "Add New Workspace": "새 워크스페이스 추가",
    "Add New...": "새로 추가...",
    "Add Pattern to .gitignore": ".gitignore에 패턴 추가",
    "Add Remote": "리모트 추가",
    "Add Remote...": "리모트 추가...",
    "Add Repository": "저장소 추가",
    "Add Repository Custom Command": "저장소 사용자 정의 명령 추가",
    "Add Sample Github Rule": "GitHub 샘플 규칙 추가",
    "Add Sample Jira Multiproject Rule": "Jira 다중 프로젝트 샘플 규칙 추가",
    "Add Sample Jira Rule": "Jira 샘플 규칙 추가",
    "Add Signed-off-by line at the end of the commit message": "커밋 메시지 끝에 Signed-off-by 줄 추가",
    "Add Skill": "스킬 추가",
    "Add Submodule": "서브모듈 추가",
    "Add Submodule Custom Command": "서브모듈 사용자 정의 명령 추가",
    "Add Submodule...": "서브모듈 추가...",
    "Add Text Box": "텍스트 상자 추가",
    "Add Track Pattern...": "추적 패턴 추가...",
    "Add Workspace": "워크스페이스 추가",
    "Add a git mm workspace to start": "시작하려면 git mm 워크스페이스를 추가하세요",
    "Add file path patterns to .gitattributes": ".gitattributes에 파일 경로 패턴 추가",
    "Add files to .gitignore": ".gitignore에 파일 추가",
    "Add hyperlinks to issue numbers in commit messages": "커밋 메시지의 이슈 번호에 하이퍼링크 추가",
    "Add new remote repository reference": "새 리모트 저장소 참조 추가",
    "Add new submodule repository reference": "새 서브모듈 저장소 참조 추가",
    "Add submodule '{0}'": "서브모듈 '{0}' 추가",
    "Add to .gitignore": ".gitignore에 추가",
    "Add tracking patterns to Git LFS": "Git LFS에 추적 패턴 추가",
    "Adding files to .gitignore...": ".gitignore에 파일 추가 중...",
    "Adding submodule...": "서브모듈 추가 중...",
    "Advanced Options": "고급 옵션",
    "Ahead of '{0}' '{1}'": "'{0}' '{1}'보다 앞섬",
    "Ahead: {0}": "앞섬: {0}",
    "All": "모두",
    "All Commits": "모든 커밋",
    "All Commits View": "모든 커밋 보기",
    "All branches": "모든 브랜치",
    "All conflicts resolved": "모든 충돌 해결됨",
    "All contributors": "모든 기여자",
    "All files (*.*)": "모든 파일 (*.*)",
    "All review results": "모든 리뷰 결과",
    "All sub repositories": "모든 하위 저장소",
    "All uncommitted changes will be lost": "커밋되지 않은 모든 변경사항이 손실됩니다",
    "All uncommitted changes will be lost.": "커밋되지 않은 모든 변경사항이 손실됩니다.",
    "All your changes will be discarded.": "모든 변경사항이 버려집니다.",
    "Allow commit": "커밋 허용",
    "Allow no tracking branch": "추적 브랜치 없음 허용",
    "Allow tag": "태그 허용",
    "Allowed parameters:": "허용된 매개변수:",
    "Alphabetically": "알파벳순",
    "Alphabetically backward": "알파벳 역순",
    "Already a git mm repository": "이미 git mm 저장소임",
    "Already a git repository": "이미 Git 저장소임",
    "Already up to date": "이미 최신 상태",
    "Also delete corresponding remote branch": "해당 리모트 브랜치도 삭제",
    "Also delete corresponding remote branches": "해당 리모트 브랜치들도 삭제",
    "Also delete remote branch": "리모트 브랜치도 삭제",
    "Also delete worktree": "워크트리도 삭제",
    "Also rename {0}": "{0}도 이름 변경",
    "Always Show Output": "항상 출력 표시",
    "Always include tags into fetch": "페치 시 항상 태그 포함",
    "Amend": "수정",
    "Amend Last Commit": "마지막 커밋 수정",
    "Amending commit that has already been pushed": "이미 푸시된 커밋 수정 중",
    "An unexpected error occured while performing the git request": "Git 요청을 수행하는 중 예기치 않은 오류가 발생했습니다",
    "Any": "모두",
    "Any File": "모든 파일",
    "Append origin to commit message": "커밋 메시지에 origin 추가",
    "Applicable suggestions": "적용 가능한 제안",
    "Applications": "응용 프로그램",
    "Applied changes": "적용된 변경사항",
    "Applied suggestion to {0}.": "{0}에 제안을 적용했습니다.",
    "Apply '{0}'...": "'{0}' 적용...",
    "Apply Patch": "패치 적용",
    "Apply Patch…": "패치 적용…",
    "Apply Stash": "스태시 적용",
    "Apply changes of the individual commit": "개별 커밋의 변경사항 적용",
    "Apply changes of the stash to your working directory": "스태시의 변경사항을 작업 디렉토리에 적용",
    "Apply patch": "패치 적용",
    "Apply patch from clipboard": "클립보드에서 패치 적용",
    "Apply stash '{0}'": "스태시 '{0}' 적용",
    "Apply stash failed": "스태시 적용 실패",
    "Apply suggestion": "제안 적용",
    "Applying a series of patches (AM) in progress": "일련의 패치(AM) 적용 진행 중",
    "Applying patch...": "패치 적용 중...",
    "Applying stash...": "스태시 적용 중...",
    "Are you sure you want to delete reference to remote '{0}'?": "리모트 '{0}'에 대한 참조를 삭제하시겠습니까?",
    "Are you sure you want to delete submodule {0}?": "서브모듈 {0}을(를) 삭제하시겠습니까?",
    "Are you sure you want to delete worktree ": "워크트리를 삭제하시겠습니까 ",
    "Are you sure you want to delete worktree {0}?": "워크트리 {0}을(를) 삭제하시겠습니까?",
    "Arguments:": "인수:",
    "Assigned to me": "나에게 할당됨",
    "Assume yes": "예로 간주",
    "Authentication Type:": "인증 유형:",
    "Author or email": "작성자 또는 이메일",
    "Authors": "작성자",
    "Automatic fetch": "자동 페치",
    "Automatic merge failed. Fix conflicts and then commit the result": "자동 병합 실패. 충돌을 해결한 후 결과를 커밋하세요",
    "Automatic status refresh": "자동 상태 새로고침",
    "Automatically fetch mounted models from URL and API key": "URL과 API 키에서 마운트된 모델을 자동으로 가져오기",
    "Available keyboard shortcuts": "사용 가능한 키보드 단축키",
    "Available variables:": "사용 가능한 변수:",
    "Available variables: $LOCAL, $REMOTE": "사용 가능한 변수: $LOCAL, $REMOTE",
    "Available variables: $LOCAL, $REMOTE, $BASE, $MERGED": "사용 가능한 변수: $LOCAL, $REMOTE, $BASE, $MERGED",
    "Back-merge master into develop": "master를 develop로 백머지",
    "Background": "백그라운드",
    "Backup current state with a temporary branch": "임시 브랜치로 현재 상태 백업",
    "Bad": "나쁨",
    "Bash Command": "Bash 명령",
    "Behind '{0}' '{1}'": "'{0}' '{1}'보다 뒤처짐",
    "Behind: {0}": "뒤처짐: {0}",
    "Benchmark": "벤치마크",
    "Benchmark...": "벤치마크...",
    "Bisect": "바이섹트",
    "Bisect: {0}": "바이섹트: {0}",
    "Bisecting, started from '": "바이섹트 중, 시작점 '",
    "BitBucket Error: {0}": "BitBucket 오류: {0}",
    "Blame": "블레임",
    "Blame can only be used for text files": "블레임은 텍스트 파일에만 사용할 수 있습니다",
    "Blame...": "블레임...",
    "Blame/Timeline...": "블레임/타임라인...",
    "Branch '{0}' already exists": "브랜치 '{0}'이(가) 이미 존재합니다",
    "Branch Selector": "브랜치 선택기",
    "Branch name": "브랜치 이름",
    "Branch name:": "브랜치 이름:",
    "Branch {0} already exists": "브랜치 {0}이(가) 이미 존재합니다",
    "Branch:": "브랜치:",
    "Branches:": "브랜치:",
    "Browse": "찾아보기",
    "Button Title": "버튼 제목",
    "Buttons:": "버튼:",
    "By date": "날짜순",
    "By default stash ignores new files until you stage them": "기본적으로 스태시는 스테이지하기 전까지 새 파일을 무시합니다",
    "CC:": "참조:",
    "COMMITTER": "커미터",
    "Can not move submodule to {0}": "서브모듈을 {0}(으)로 이동할 수 없습니다",
    "Cancel background fetch...": "백그라운드 페치 취소...",
    "Cancel...": "취소...",
    "Canceling...": "취소 중...",
    "Cancelled": "취소됨",
    "Cannot apply suggestion because the target text was not found in {0}.": "{0}에서 대상 텍스트를 찾을 수 없어 제안을 적용할 수 없습니다.",
    "Cannot create slug for '{0}'": "'{0}'에 대한 slug를 생성할 수 없습니다",
    "Cannot find file: {0}": "파일을 찾을 수 없습니다: {0}",
    "Cannot find git instance at: '{0}'": "'{0}'에서 git 인스턴스를 찾을 수 없습니다",
    "Cannot find git instance at: '{0}'. Missing bash.exe": "'{0}'에서 git 인스턴스를 찾을 수 없습니다. bash.exe가 없습니다",
    "Cannot find git instance at: '{0}'. Missing sh.exe": "'{0}'에서 git 인스턴스를 찾을 수 없습니다. sh.exe가 없습니다",
    "Cannot find private key: '{0}'": "개인 키를 찾을 수 없습니다: '{0}'",
    "Cannot find public key: '{0}'": "공개 키를 찾을 수 없습니다: '{0}'",
    "Cannot get diff:\n": "diff를 가져올 수 없습니다:\n",
    "Cannot save authentication": "인증 정보를 저장할 수 없습니다",
    "Cannot sync: You have unstaged changes. Please commit or stash them.": "동기화할 수 없습니다: 스테이지되지 않은 변경사항이 있습니다. 커밋하거나 스태시하세요.",
    "Change": "변경",
    "Change branch remote tracking reference": "브랜치 리모트 추적 참조 변경",
    "Change the avatar at": "다음에서 아바타 변경",
    "Change tracking reference": "추적 참조 변경",
    "Changed repositories": "변경된 저장소",
    "Changed: {0}": "변경됨: {0}",
    "Changes": "변경사항",
    "Changes View": "변경사항 보기",
    "Changes are too large (": "변경사항이 너무 큽니다 (",
    "Check Box Details": "체크박스 세부정보",
    "Check Box Title": "체크박스 제목",
    "Check out after create": "생성 후 체크아웃",
    "Checked Value:": "선택된 값:",
    "Checked by default": "기본적으로 선택됨",
    "Checking files": "파일 확인 중",
    "Checking out files": "파일 체크아웃 중",
    "Checkout '{0}'": "'{0}' 체크아웃",
    "Checkout '{0}' as Worktree...": "'{0}'을(를) 워크트리로 체크아웃...",
    "Checkout Branch": "브랜치 체크아웃",
    "Checkout Branch As Worktree": "브랜치를 워크트리로 체크아웃",
    "Checkout Branch as Worktree": "브랜치를 워크트리로 체크아웃",
    "Checkout Commit": "커밋 체크아웃",
    "Checkout Commit...": "커밋 체크아웃...",
    "Checkout a particular revision. Repository will be in detached HEAD state.": "특정 리비전을 체크아웃합니다. 저장소가 분리된 HEAD 상태가 됩니다.",
    "Checkout and Fast-Forward": "체크아웃 및 패스트포워드",
    "Checkout and Merge": "체크아웃 및 병합",
    "Checkout and Rebase": "체크아웃 및 리베이스",
    "Checkout and Reset": "체크아웃 및 재설정",
    "Checkout as Worktree...": "워크트리로 체크아웃...",
    "Checkout branch '{0}'": "브랜치 '{0}' 체크아웃",
    "Checkout branch as worktree failed": "브랜치를 워크트리로 체크아웃 실패",
    "Checkout branch in separate worktree": "별도의 워크트리에서 브랜치 체크아웃",
    "Checkout jobs:": "체크아웃 작업:",
    "Checkout local branch and fast-forward it to remote branch": "로컬 브랜치를 체크아웃하고 리모트 브랜치로 패스트포워드",
    "Checkout...": "체크아웃...",
    "Cherry Pick {0} commits": "{0}개 커밋 체리픽",
    "Cherry Pick...": "체리픽...",
    "Cherry-pick": "체리픽",
    "Cherry-pick Commit...": "커밋 체리픽...",
    "Cherry-pick in progress": "체리픽 진행 중",
    "Cherry-picking commit '": "커밋 체리픽 중 '",
    "Cherry-picking...": "체리픽 중...",
    "Cherry-pick…": "체리픽…",
    "Choose {0}": "{0} 선택",
    "Clear Branch Filter": "브랜치 필터 지우기",
    "Clear Recents": "최근 항목 지우기",
    "Clear commit message": "커밋 메시지 지우기",
    "Clear filter": "필터 지우기",
    "Clear repository filter": "저장소 필터 지우기",
    "Click to show matching repositories": "클릭하여 일치하는 저장소 표시",
    "Clone a remote repository into a local folder": "리모트 저장소를 로컬 폴더에 클론",
    "Clone new repository": "새 저장소 클론",
    "Clone...": "클론...",
    "Cloning {0}...": "{0} 클론 중...",
    "Close All": "모두 닫기",
    "Close All But This": "이 탭을 제외하고 모두 닫기",
    "Close Tab": "탭 닫기",
    "Close current tab": "현재 탭 닫기",
    "Code AI Review": "코드 AI 리뷰",
    "Code AI Review is not implemented yet.": "코드 AI 리뷰는 아직 구현되지 않았습니다.",
    "Code AI Review...": "코드 AI 리뷰...",
    "Code Review with {0}...": "{0}(으)로 코드 리뷰...",
    "Code review for {0} files": "{0}개 파일에 대한 코드 리뷰",
    "Code review for {0}...{1}": "코드 리뷰: {0}...{1}",
    "Code review for {0}..{1}": "코드 리뷰: {0}..{1}",
    "Collapse": "접기",
    "Collapse All": "모두 접기",
    "Collapse All Merges (Show First Parent)": "모든 병합 접기(첫 번째 부모 표시)",
    "Collecting {0}": "{0} 수집 중",
    "Command": "명령",
    "Command Output": "명령 출력",
    "Command Preview:": "명령 미리보기:",
    "Command failed": "명령 실패",
    "Command reference for git mm start, sync, and upload.": "git mm start, sync, upload의 명령 참조.",
    "Command running": "명령 실행 중",
    "Command succeeded": "명령 성공",
    "Command:": "명령:",
    "Commands": "명령",
    "Commit List Layout": "커밋 목록 레이아웃",
    "Commit Message": "커밋 메시지",
    "Commit Options": "커밋 옵션",
    "Commit Settings": "커밋 설정",
    "Commit Template": "커밋 템플릿",
    "Commit and Push": "커밋 및 푸시",
    "Commit and push": "커밋 및 푸시",
    "Commit message": "커밋 메시지",
    "Commit message does not match configured regex: {0}": "커밋 메시지가 구성된 정규식과 일치하지 않습니다: {0}",
    "Commit message regex:": "커밋 메시지 정규식:",
    "Commit search": "커밋 검색",
    "Commit subject": "커밋 제목",
    "Commit the changes": "변경사항 커밋",
    "Commit title": "커밋 제목",
    "Commit title:": "커밋 제목:",
    "Commit to apply:": "적용할 커밋:",
    "Commit to checkout:": "체크아웃할 커밋:",
    "Commit {0} File": "{0}개 파일 커밋",
    "Commit {0} Files": "{0}개 파일 커밋",
    "Commits": "커밋",
    "Commits per day hour": "시간당 커밋 수",
    "Commits per month": "월별 커밋 수",
    "Commits per weekday": "요일별 커밋 수",
    "Commits to apply:": "적용할 커밋:",
    "Commits:": "커밋:",
    "Common location": "공통 위치",
    "Compact branch labels": "간결한 브랜치 라벨",
    "Compare to Local Changes": "로컬 변경사항과 비교",
    "Compressing objects": "객체 압축 중",
    "Configure Git": "Git 설정",
    "Configure SSH Keys": "SSH 키 설정",
    "Configure SSH Keys...": "SSH 키 설정...",
    "Configure...": "설정...",
    "Conflicts: {0}": "충돌: {0}",
    "Connecting...": "연결 중...",
    "Connection succeeded": "연결 성공",
    "Consider adding a .gitignore file to your repository": "저장소에 .gitignore 파일을 추가하는 것을 권장합니다",
    "Console": "콘솔",
    "Content:": "내용:",
    "Context search '{0}'": "컨텍스트 검색 '{0}'",
    "Continue Am": "AM 계속",
    "Continue Cherry-Pick": "체리픽 계속",
    "Continue Rebase": "리베이스 계속",
    "Continue Sync": "동기화 계속",
    "Control Title": "컨트롤 제목",
    "Control Type:": "컨트롤 유형:",
    "Controls:": "컨트롤:",
    "Copy Branch Name": "브랜치 이름 복사",
    "Copy Commit Info": "커밋 정보 복사",
    "Copy Commit SHA": "커밋 SHA 복사",
    "Copy Full Path": "전체 경로 복사",
    "Copy Link": "링크 복사",
    "Copy Path": "경로 복사",
    "Copy Remote Address": "리모트 주소 복사",
    "Copy Tag Name": "태그 이름 복사",
    "Copy as Patch": "패치로 복사",
    "Copy commit info": "커밋 정보 복사",
    "Copy commits from one branch to another": "한 브랜치에서 다른 브랜치로 커밋 복사",
    "Copy report": "보고서 복사",
    "Copy selected file full path": "선택한 파일의 전체 경로 복사",
    "Copy to clipboard": "클립보드에 복사",
    "Copyright © {0} Hebin": "Copyright © {0} Hebin",
    "Could not resolve host '{0}'": "호스트 '{0}'을(를) 확인할 수 없습니다",
    "Counting objects": "객체 계산 중",
    "Country, region, or territory not supported": "지원되지 않는 국가, 지역 또는 영토",
    "Create Branch": "브랜치 생성",
    "Create Branch...": "브랜치 생성...",
    "Create Patch": "패치 생성",
    "Create Pull Request": "풀 리퀘스트 생성",
    "Create Pull Request on '{0}'...": "'{0}'에 풀 리퀘스트 생성...",
    "Create Tag": "태그 생성",
    "Create Tag...": "태그 생성...",
    "Create Worktree": "워크트리 생성",
    "Create Worktree...": "워크트리 생성...",
    "Create a new feature branch based on 'develop' and switch to it": "'develop'을 기반으로 새 기능 브랜치를 생성하고 전환",
    "Create a new hotfix branch based on 'master' and switch to it": "'master'를 기반으로 새 핫픽스 브랜치를 생성하고 전환",
    "Create a new release branch based on 'develop' and switch to it": "'develop'을 기반으로 새 릴리스 브랜치를 생성하고 전환",
    "Create and Checkout": "생성 및 체크아웃",
    "Create and Push": "생성 및 푸시",
    "Create and push tag '{0}'": "태그 '{0}' 생성 및 푸시",
    "Create annotated tag at the selected point": "선택한 지점에 주석이 달린 태그 생성",
    "Create branch '{0}'": "브랜치 '{0}' 생성",
    "Create branch and checkout it in a separate worktree": "브랜치를 생성하고 별도의 워크트리에서 체크아웃",
    "Create branch at:": "다음 지점에 브랜치 생성:",
    "Create commit": "커밋 생성",
    "Create new local branch which tracks remote branch": "리모트 브랜치를 추적하는 새 로컬 브랜치 생성",
    "Create stash": "스태시 생성",
    "Create tag '{0}'": "태그 '{0}' 생성",
    "Create tag at:": "다음 지점에 태그 생성:",
    "Create tracking reference": "추적 참조 생성",
    "Create worktree failed": "워크트리 생성 실패",
    "Creating '{0}'...": "'{0}' 생성 중...",
    "Creating branch '{0}'": "브랜치 '{0}' 생성 중",
    "Creating branch...": "브랜치 생성 중...",
    "Creating worktree...": "워크트리 생성 중...",
    "Credential Manager": "자격 증명 관리자",
    "Credentials Required": "자격 증명 필요",
    "Ctrl+Enter to add": "Ctrl+Enter로 추가",
    "Current Branch": "현재 브랜치",
    "Current branch only": "현재 브랜치만",
    "Current file": "현재 파일",
    "Currently Fork doesn't support 32-bit Windows": "현재 Fork는 32비트 Windows를 지원하지 않습니다",
    "Custom Git Instance...": "사용자 정의 Git 인스턴스...",
    "Custom Pattern...": "사용자 정의 패턴...",
    "Custom Remote Branch Name": "사용자 정의 리모트 브랜치 이름",
    "Custom...": "사용자 정의...",
    "Cut": "잘라내기",
    "Dark": "어둡게",
    "Deactivate": "비활성화",
    "Deactivating...": "비활성화 중...",
    "Decrease number of visible lines": "표시 줄 수 줄이기",
    "Default Directory (relative or absolute, optional)": "기본 디렉토리(상대 또는 절대 경로, 선택 사항)",
    "Default Directory:": "기본 디렉토리:",
    "Default Extension (optional)": "기본 확장자(선택 사항)",
    "Default Extension:": "기본 확장자:",
    "Default File Name (optional)": "기본 파일 이름(선택 사항)",
    "Default Value (optional)": "기본값(선택 사항)",
    "Default source folder path": "기본 소스 폴더 경로",
    "Default source folder:": "기본 소스 폴더:",
    "Default: {0}": "기본: {0}",
    "Deinitialize Git Flow": "Git Flow 초기화 해제",
    "Deinitialize Git LFS": "Git LFS 초기화 해제",
    "Delete '{0}'": "'{0}' 삭제",
    "Delete '{0}'...": "'{0}' 삭제...",
    "Delete Branch": "브랜치 삭제",
    "Delete Branch...": "브랜치 삭제...",
    "Delete Branches": "브랜치 삭제",
    "Delete Stash": "스태시 삭제",
    "Delete Stashes": "스태시 삭제",
    "Delete Submodule": "서브모듈 삭제",
    "Delete Tag": "태그 삭제",
    "Delete Tag...": "태그 삭제...",
    "Delete Tags": "태그 삭제",
    "Delete branch from remote repository": "리모트 저장소에서 브랜치 삭제",
    "Delete branches": "브랜치 삭제",
    "Delete branches from remote repository": "리모트 저장소에서 브랜치 삭제",
    "Delete file": "파일 삭제",
    "Delete local branch from your repository": "저장소에서 로컬 브랜치 삭제",
    "Delete local branches from your repository": "저장소에서 로컬 브랜치 삭제",
    "Delete remote '{0}'": "리모트 '{0}' 삭제",
    "Delete stash after applying": "적용 후 스태시 삭제",
    "Delete stash from your repository": "저장소에서 스태시 삭제",
    "Delete stashes from your repository": "저장소에서 스태시 삭제",
    "Delete submodule": "서브모듈 삭제",
    "Delete submodule '{0}'": "서브모듈 '{0}' 삭제",
    "Delete tag from remote repositories": "리모트 저장소에서 태그 삭제",
    "Delete tag from your repository": "저장소에서 태그 삭제",
    "Delete tags from remote repositories": "리모트 저장소에서 태그 삭제",
    "Delete tags from your repository": "저장소에서 태그 삭제",
    "Delete worktree '{0}'": "워크트리 '{0}' 삭제",
    "Delete {0} Branches...": "{0}개 브랜치 삭제...",
    "Delete {0} Remote Branches...": "{0}개 리모트 브랜치 삭제...",
    "Delete {0} Stashes...": "{0}개 스태시 삭제...",
    "Delete {0} Tags...": "{0}개 태그 삭제...",
    "Delete {0} branches": "{0}개 브랜치 삭제",
    "Delete {0} stashes": "{0}개 스태시 삭제",
    "Delete {0} tags": "{0}개 태그 삭제",
    "Delete...": "삭제...",
    "Deleting '{0}'...": "'{0}' 삭제 중...",
    "Deleting submodule...": "서브모듈 삭제 중...",
    "Deleting worktree...": "워크트리 삭제 중...",
    "Deleting {0} remote branches...": "{0}개 리모트 브랜치 삭제 중...",
    "Deleting...": "삭제 중...",
    "Describe your development needs. AI will generate code and show the changes.": "개발 요구사항을 설명하세요. AI가 코드를 생성하고 변경사항을 표시합니다.",
    "Description:": "설명:",
    "Designed and implemented by": "디자인 및 구현",
    "Destination folder is not empty": "대상 폴더가 비어 있지 않습니다",
    "Detach local branches": "로컬 브랜치 분리",
    "Details:": "세부정보:",
    "Detected Git:": "감지된 Git:",
    "Detected {0} models.": "{0}개 모델이 감지되었습니다.",
    "Development Branch:": "개발 브랜치:",
    "Development branch name can't be empty": "개발 브랜치 이름은 비워둘 수 없습니다",
    "Dialog Type:": "대화상자 유형:",
    "Dialog description": "대화상자 설명",
    "Dialog title": "대화상자 제목",
    "Diff Content": "diff 내용",
    "Diff View": "diff 보기",
    "Diff in {0}": "{0}(으)로 diff",
    "Disable": "비활성화",
    "Disable Refresh on Activation": "활성화 시 새로고침 비활성화",
    "Disable syntax highlighting": "구문 강조 비활성화",
    "Discard All": "모두 버리기",
    "Discard Changes": "변경사항 버리기",
    "Discard Changes in {0} Files": "{0}개 파일의 변경사항 버리기",
    "Discard Line": "이 줄 버리기",
    "Discard Submodules": "서브모듈 변경사항 버리기",
    "Discard all changes in '{0}'?": "'{0}'의 모든 변경사항을 버리시겠습니까?",
    "Discard all local changes": "모든 로컬 변경사항 버리기",
    "Discard changes": "변경사항 버리기",
    "Discard changes...": "변경사항 버리기...",
    "Discard local changes (--force)": "로컬 변경사항 버리기(--force)",
    "Discard local sync state and force git mm to resync projects.": "로컬 동기화 상태를 버리고 git mm이 프로젝트를 다시 동기화하도록 강제합니다.",
    "Discard selected file (or lines)": "선택한 파일(또는 줄) 버리기",
    "Discard submodule changes...": "서브모듈 변경사항 버리기...",
    "Discard {0} Lines": "{0}줄 버리기",
    "Discard...": "버리기...",
    "Do not require commit message": "커밋 메시지 불필요",
    "Do you really want to cancel Interactive Rebase?": "대화형 리베이스를 정말 취소하시겠습니까?",
    "Do you want reset file to unmerged state?": "파일을 병합되지 않은 상태로 재설정하시겠습니까?",
    "Do you want to abort applying patches?": "패치 적용을 중단하시겠습니까?",
    "Do you want to abort cherry-pick?": "체리픽을 중단하시겠습니까?",
    "Do you want to abort revert?": "되돌리기를 중단하시겠습니까?",
    "Do you want to abort the merge?": "병합을 중단하시겠습니까?",
    "Do you want to abort the rebase?": "리베이스를 중단하시겠습니까?",
    "Do you want to delete '{0}'?": "'{0}'을(를) 삭제하시겠습니까?",
    "Do you want to delete submodule {0}?": "서브모듈 {0}을(를) 삭제하시겠습니까?",
    "Do you want to delete the workspace '{0}'?": "워크스페이스 '{0}'을(를) 삭제하시겠습니까?",
    "Do you want to delete worktree ": "워크트리를 삭제하시겠습니까 ",
    "Do you want to delete worktree {0}?": "워크트리 {0}을(를) 삭제하시겠습니까?",
    "Do you want to discard all your changes in the selected files?": "선택한 파일의 모든 변경사항을 버리시겠습니까?",
    "Do you want to discard all your changes in the selected lines?": "선택한 줄의 모든 변경사항을 버리시겠습니까?",
    "Do you want to discard changes in the submodule?": "서브모듈의 변경사항을 버리시겠습니까?",
    "Do you want to discard changes in {0} submodules?": "{0}개 서브모듈의 변경사항을 버리시겠습니까?",
    "Do you want to remove the selected control?": "선택한 컨트롤을 제거하시겠습니까?",
    "Do you want to remove the selected custom command?": "선택한 사용자 정의 명령을 제거하시겠습니까?",
    "Do you want to remove the selected external tool?": "선택한 외부 도구를 제거하시겠습니까?",
    "Do you want to remove the selected folders from Fork?": "선택한 폴더를 Fork에서 제거하시겠습니까?",
    "Do you want to remove the selected issue tracker rule?": "선택한 이슈 트래커 규칙을 제거하시겠습니까?",
    "Do you want to remove the selected repository from Fork?": "선택한 저장소를 Fork에서 제거하시겠습니까?",
    "Do you want to remove the selected source directory?": "선택한 소스 디렉토리를 제거하시겠습니까?",
    "Do you want to remove {0} selected repositories from Fork?": "선택한 {0}개 저장소를 Fork에서 제거하시겠습니까?",
    "Do you want to rescan repositories in '{0}'?": "'{0}'의 저장소를 다시 스캔하시겠습니까?",
    "Do you want to reset the file to the state it is at the commit?": "파일을 커밋 시점의 상태로 재설정하시겠습니까?",
    "Do you want to reset the file to the state it was before the commit?": "파일을 커밋 전의 상태로 재설정하시겠습니까?",
    "Do you want to reset {0} files to the state they are at the commit?": "{0}개 파일을 커밋 시점의 상태로 재설정하시겠습니까?",
    "Do you want to reset {0} files to the state they were before the commit?": "{0}개 파일을 커밋 전의 상태로 재설정하시겠습니까?",
    "Don't change": "변경 안 함",
    "Done": "완료",
    "Done.": "완료.",
    "Download Git LFS objects for the currently checked out ref, and update the working directory with the downloaded content if required": "현재 체크아웃된 ref의 Git LFS 객체를 다운로드하고, 필요한 경우 다운로드한 내용으로 작업 디렉토리를 업데이트",
    "Download Git LFS objects from the specified remotes": "지정된 리모트에서 Git LFS 객체 다운로드",
    "Downloading {0}": "{0} 다운로드 중",
    "Drop": "버리기",
    "Drop repository here to add": "저장소를 여기에 놓아 추가",
    "Drop...": "버리기...",
    "Dropdown Title": "드롭다운 제목",
    "Drop…": "버리기…",
    "Edit Action": "동작 편집",
    "Edit Custom Command UI Controls": "사용자 정의 명령 UI 컨트롤 편집",
    "Edit Remote": "리모트 편집",
    "Edit URL of the remote repository": "리모트 저장소 URL 편집",
    "Edit custom command action": "사용자 정의 명령 동작 편집",
    "Edit the commit message": "커밋 메시지 편집",
    "Edit...": "편집...",
    "Edit…": "편집…",
    "Email": "이메일",
    "Email:": "이메일:",
    "Enable Issue Tracker Integration in Fork preferences": "Fork 환경설정에서 이슈 트래커 연동 활성화",
    "Enable Notifications": "알림 활성화",
    "Enable verbose Git output": "상세 Git 출력 활성화",
    "English": "영어",
    "Enjoy using Fork!": "Fork를 즐겁게 사용하세요!",
    "Enter a branch name": "브랜치 이름을 입력하세요",
    "Enter branch name": "브랜치 이름 입력",
    "Enter custom destination": "사용자 정의 대상 입력",
    "Enter hotfix message (optional)": "핫픽스 메시지 입력(선택 사항)",
    "Enter manifest repository URL": "매니페스트 저장소 URL 입력",
    "Enter new branch name": "새 브랜치 이름 입력",
    "Enter new stash message": "새 스태시 메시지 입력",
    "Enter passphrase for SSH key '{0}'": "SSH 키 '{0}'의 암호 입력",
    "Enter release message (optional)": "릴리스 메시지 입력(선택 사항)",
    "Enter tag message (optional)": "태그 메시지 입력(선택 사항)",
    "Enter tag name": "태그 이름 입력",
    "Enter your request": "요청을 입력하세요",
    "Enumerating objects": "객체 나열 중",
    "Environment Git": "환경 변수 Git",
    "Error: {0}": "오류: {0}",
    "Executable files": "실행 파일",
    "Exit": "종료",
    "Exit code: {0}": "종료 코드: {0}",
    "Expand": "펼치기",
    "Expand All": "모두 펼치기",
    "Expand Command Output": "명령 출력 펼치기",
    "External Diff": "외부 diff",
    "External Diff Tools": "외부 diff 도구",
    "External Merge": "외부 병합",
    "External Merge Tools": "외부 병합 도구",
    "External diff": "외부 diff",
    "External tool": "외부 도구",
    "External tool arguments": "외부 도구 인수",
    "External tool location": "외부 도구 위치",
    "External tool name": "외부 도구 이름",
    "Fail fast": "빠른 실패",
    "Failed repositories": "실패한 저장소",
    "Failed to create destination folder": "대상 폴더 생성 실패",
    "Failed to load file '{0}': {1}": "파일 '{0}' 로드 실패: {1}",
    "Failed to load file: {0}": "파일 로드 실패: {0}",
    "Fast forward '{0}'": "'{0}' 패스트포워드",
    "Fast-Forward": "패스트포워드",
    "Fast-Forward to '{0}'": "'{0}'(으)로 패스트포워드",
    "Fast-Forward to:": "패스트포워드 대상:",
    "Fast-forward '{0}' to '{1}'": "'{0}'을(를) '{1}'(으)로 패스트포워드",
    "Fast-forward failed": "패스트포워드 실패",
    "Feature Name": "기능 이름",
    "Feature Prefix:": "기능 접두사:",
    "Feature branch prefix can't be empty": "기능 브랜치 접두사는 비워둘 수 없습니다",
    "Feature:": "기능:",
    "Fetch '{0}'": "'{0}' 페치",
    "Fetch '{0}' Automatically": "'{0}' 자동 페치",
    "Fetch '{0}'...": "'{0}' 페치...",
    "Fetch all": "모두 페치",
    "Fetch all remotes": "모든 리모트 페치",
    "Fetch jobs:": "페치 작업:",
    "Fetch latest changes from remote repository": "리모트 저장소에서 최신 변경사항 페치",
    "Fetch nested submodules": "중첩 서브모듈 페치",
    "Fetch remotes automatically": "리모트 자동 페치",
    "Fetch submodules": "서브모듈 페치",
    "Fetch tags": "태그 페치",
    "Fetch...": "페치...",
    "Fetched {0} branch": "{0}개 브랜치 페치됨",
    "Fetched {0} branches": "{0}개 브랜치 페치됨",
    "Fetching LFS files...": "LFS 파일 페치 중...",
    "Fetching nested submodules...": "중첩 서브모듈 페치 중...",
    "Fetching...": "페치 중...",
    "File History...": "파일 기록...",
    "File Name (optional)": "파일 이름(선택 사항)",
    "File Name:": "파일 이름:",
    "File Path": "파일 경로",
    "File Tree": "파일 트리",
    "File conflicts are resolved.": "파일 충돌이 해결되었습니다.",
    "File is {0} and is not managed by LFS": "파일은 {0}이며 LFS에서 관리되지 않습니다",
    "Filter By Active Branch": "현재 브랜치로 필터",
    "Filter Issues": "이슈 필터",
    "Filter Pull Requests": "풀 리퀘스트 필터",
    "Filter by Active Branch": "현재 브랜치로 필터",
    "Filter by active branch": "현재 브랜치로 필터",
    "Filter:": "필터:",
    "Filtered by:": "필터 조건:",
    "Find": "찾기",
    "Finish '{0}'": "'{0}' 완료",
    "Finish '{0}' (Merge into '{1}')...": "'{0}' 완료('{1}'에 병합)...",
    "Finish '{0}' and merge it into '{1}'": "'{0}'을(를) 완료하고 '{1}'에 병합",
    "Finish '{0}'...": "'{0}' 완료...",
    "Finish (Merge into '{0}')...": "완료('{0}'에 병합)...",
    "Finish Feature...": "기능 완료...",
    "Finish Git Flow feature": "Git Flow 기능 완료",
    "Finish Git Flow hotfix": "Git Flow 핫픽스 완료",
    "Finish Git Flow release": "Git Flow 릴리스 완료",
    "Finish Hotfix...": "핫픽스 완료...",
    "Finish Release...": "릴리스 완료...",
    "Finish the feature and merge it into the develop branch": "기능을 완료하고 develop 브랜치에 병합",
    "Finish the hotfix and merge it into the develop and master branches": "핫픽스를 완료하고 develop 및 master 브랜치에 병합",
    "Finish the release and merge it into the develop and master branches": "릴리스를 완료하고 develop 및 master 브랜치에 병합",
    "Finishing {0}...": "{0} 완료 중...",
    "Fix {0} {1} and then continue.": "{0}개 {1}을(를) 해결한 후 계속하세요.",
    "Fix {0} {1} with '": "{0}개 {1} 해결, 관련 커밋 '",
    "Fixup": "픽스업",
    "Fixup into Parent": "부모에 픽스업",
    "Fixup into Parent...": "부모에 픽스업...",
    "Fixup into Parent…": "부모에 픽스업…",
    "Focus commit message field": "커밋 메시지 입력란 포커스",
    "Folder:": "폴더:",
    "Font size:": "글꼴 크기:",
    "For example: fork_ssh_key": "예: fork_ssh_key",
    "Force Fetch": "강제 페치",
    "Force LFS Unlock": "강제 LFS 잠금 해제",
    "Force Unlock": "강제 잠금 해제",
    "Force Unlock {0} Files": "{0}개 파일 강제 잠금 해제",
    "Force checkout": "강제 체크아웃",
    "Force fetch": "강제 페치",
    "Force sync": "강제 동기화",
    "Force upload": "강제 업로드",
    "Force upload even if git mm reports safety checks.": "git mm이 안전 검사를 보고해도 강제 업로드합니다.",
    "Fork will not look for repositories in this folder automatically": "Fork는 이 폴더에서 자동으로 저장소를 찾지 않습니다",
    "ForkPlus Git": "ForkPlus Git",
    "ForkPlus requires a valid Git executable to continue.": "ForkPlus를 계속하려면 유효한 Git 실행 파일이 필요합니다.",
    "Fri": "금",
    "Full name (optional)": "전체 이름(선택 사항)",
    "Full reference filter (e.g. 'refs/heads/')": "전체 참조 필터(예: 'refs/heads/')",
    "General Navigation": "일반 탐색",
    "Generate": "생성",
    "Generate Commit Message": "커밋 메시지 생성",
    "Generate commit message": "커밋 메시지 생성",
    "Generate commit message with {0}": "{0}(으)로 커밋 메시지 생성",
    "Generate new ED25519 key": "새 ED25519 키 생성",
    "Generate new SSH Key": "새 SSH 키 생성",
    "Generating statistics...": "통계 생성 중...",
    "Generating...": "생성 중...",
    "Generic": "일반",
    "Generic Text Box": "일반 텍스트 상자",
    "Get Commit template": "커밋 템플릿 가져오기",
    "Get Revision Storage": "리비전 저장소 가져오기",
    "Get issues": "이슈 가져오기",
    "Get pull requests": "풀 리퀘스트 가져오기",
    "Get repositories": "저장소 가져오기",
    "Get user": "사용자 가져오기",
    "GetConflictDetails": "충돌 세부정보 가져오기",
    "Git Error": "Git 오류",
    "Git Flow": "Git Flow",
    "Git Flow: Finish Feature...": "Git Flow: 기능 완료...",
    "Git Flow: Finish Hotfix...": "Git Flow: 핫픽스 완료...",
    "Git Flow: Finish Release...": "Git Flow: 릴리스 완료...",
    "Git Flow: Initialize...": "Git Flow: 초기화...",
    "Git Flow: Start Feature...": "Git Flow: 기능 시작...",
    "Git Flow: Start Hotfix...": "Git Flow: 핫픽스 시작...",
    "Git Flow: Start Release...": "Git Flow: 릴리스 시작...",
    "Git Instance:": "Git 인스턴스:",
    "Git LFS": "Git LFS",
    "Git LFS: Fetch...": "Git LFS: 페치...",
    "Git LFS: Lock": "Git LFS: 잠금",
    "Git LFS: Prune": "Git LFS: 정리",
    "Git LFS: Pull...": "Git LFS: 풀...",
    "Git LFS: Status...": "Git LFS: 상태...",
    "Git LFS: Unlock": "Git LFS: 잠금 해제",
    "Git Patch": "Git 패치",
    "Git Repository Url": "Git 저장소 URL",
    "Git executable:": "Git 실행 파일:",
    "Global User Information": "전역 사용자 정보",
    "Go": "이동",
    "Go Back": "뒤로",
    "Go Forward": "앞으로",
    "Go To Line": "줄로 이동",
    "Go to next change": "다음 변경사항으로 이동",
    "Go to previous change": "이전 변경사항으로 이동",
    "Good": "좋음",
    "Hard": "하드",
    "Has conflicts": "충돌 있음",
    "Has local changes": "로컬 변경사항 있음",
    "Hidden: {0}": "숨겨짐: {0}",
    "Hide": "숨기기",
    "Hide Stashes in Commit List": "커밋 목록에서 스태시 숨기기",
    "Hide Tags": "태그 숨기기",
    "Hide Untracked Files": "추적되지 않은 파일 숨기기",
    "High limit:": "상한값:",
    "Highlight issue tracker links in commit messages": "커밋 메시지에서 이슈 트래커 링크 강조",
    "Highlight pixels": "픽셀 강조",
    "History": "기록",
    "History for Selected Lines": "선택한 줄의 기록",
    "History...": "기록...",
    "History... ": "기록... ",
    "Hold Ctrl for Quick Fetch": "빠른 페치는 Ctrl 키 누름",
    "Hold Ctrl for Quick Pull": "빠른 풀은 Ctrl 키 누름",
    "Hold Ctrl for Quick Push": "빠른 푸시는 Ctrl 키 누름",
    "Hold Ctrl for Quick Start": "빠른 시작은 Ctrl 키 누름",
    "Hold Ctrl for Quick Sync": "빠른 동기화는 Ctrl 키 누름",
    "Hold Ctrl for Quick Upload": "빠른 업로드는 Ctrl 키 누름",
    "Hold Shift to not reapply": "다시 적용하지 않으려면 Shift 키 누름",
    "Home": "홈",
    "Horizontal": "가로",
    "Hotfix Name": "핫픽스 이름",
    "Hotfix Prefix:": "핫픽스 접두사:",
    "Hotfix branch prefix can't be empty": "핫픽스 브랜치 접두사는 비워둘 수 없습니다",
    "Hotfix:": "핫픽스:",
    "Ignore": "무시",
    "Ignore '{0}'": "'{0}' 무시",
    "Ignore All": "모두 무시",
    "Ignore All {0} Files...": "모든 {0} 파일 무시...",
    "Ignore all files in '{0}'...": "'{0}'의 모든 파일 무시...",
    "Ignore whitespaces": "공백 무시",
    "Import:": "가져오기:",
    "Included repositories will be removed from Fork.": "포함된 저장소가 Fork에서 제거됩니다.",
    "Incorrect passphrase": "암호가 올바르지 않습니다",
    "Increase number of visible lines": "표시 줄 수 늘리기",
    "Inference service URL:": "추론 서비스 URL:",
    "Init": "초기화",
    "Init New Repository...": "새 저장소 초기화...",
    "Init new repository": "새 저장소 초기화",
    "Initial Commit:": "초기 커밋:",
    "Initialize": "초기화",
    "Initialize Git Flow": "Git Flow 초기화",
    "Initialize Git Flow...": "Git Flow 초기화...",
    "Initialize Git LFS": "Git LFS 초기화",
    "Initialize a git mm workspace from a manifest repository": "매니페스트 저장소에서 git mm 워크스페이스 초기화",
    "Initialize git mm Repository": "git mm 저장소 초기화",
    "Initialize git mm Repository...": "git mm 저장소 초기화...",
    "Initialize git repository here": "여기에 Git 저장소 초기화",
    "Initializing Git Flow...": "Git Flow 초기화 중...",
    "Initializing git mm repository...": "git mm 저장소 초기화 중...",
    "Interactive Rebase": "대화형 리베이스",
    "Interactively Rebase '{0}' on '{1}...": "'{0}'을(를) '{1}'에 대화형 리베이스...",
    "Interactively Rebase '{0}' to Here...": "'{0}'을(를) 여기까지 대화형 리베이스...",
    "Into:": "대상:",
    "Invalid directory": "잘못된 디렉토리",
    "Invalid git binary: '{0}'": "잘못된 git 바이너리: '{0}'",
    "Invert repository selection": "저장소 선택 반전",
    "Is '{0}' location safe?": "'{0}' 위치가 안전합니까?",
    "Issue Tracker": "이슈 트래커",
    "Issue Tracker Integration": "이슈 트래커 연동",
    "Issue Tracker Integration is disabled": "이슈 트래커 연동이 비활성화되었습니다",
    "Issue tracker integration for '{0}' is disabled": "'{0}'의 이슈 트래커 연동이 비활성화되었습니다",
    "Issues": "이슈",
    "It looks like '{0}' was deleted or moved. Do you want to remove the reference from Fork?": "'{0}'이(가) 삭제되거나 이동된 것 같습니다. Fork에서 참조를 제거하시겠습니까?",
    "It's not a good idea to make your source folder a repository. Please create a subfolder instead.": "소스 폴더를 저장소로 만드는 것은 좋지 않습니다. 대신 하위 폴더를 생성하세요.",
    "Jobs:": "작업:",
    "Jump to HEAD": "HEAD로 이동",
    "Jump to next search result": "다음 검색 결과로 이동",
    "Jump to previous search result": "이전 검색 결과로 이동",
    "Keep all changes. Stage differences": "모든 변경사항 유지. 차이점 스테이지",
    "Keep all changes. Unstage differences": "모든 변경사항 유지. 차이점 스테이지 해제",
    "Key File Name:": "키 파일 이름:",
    "Keyboard Shortcuts": "키보드 단축키",
    "LFS": "LFS",
    "LFS Fetch {0}": "LFS 페치 {0}",
    "LFS Files Status": "LFS 파일 상태",
    "LFS Lock": "LFS 잠금",
    "LFS Locks": "LFS 잠금",
    "LFS Prune": "LFS 정리",
    "LFS Pull {0}": "LFS 풀 {0}",
    "LFS Unlock": "LFS 잠금 해제",
    "LFS files": "LFS 파일",
    "LFS lock failed": "LFS 잠금 실패",
    "LFS unlock failed": "LFS 잠금 해제 실패",
    "Language:": "언어:",
    "Large file lists can take a while to render.": "큰 파일 목록은 렌더링에 시간이 걸릴 수 있습니다.",
    "Last Commit:": "마지막 커밋:",
    "Later": "나중에",
    "Leave as stash": "스태시로 유지",
    "Legal": "법적 정보",
    "Length indicator:": "길이 표시:",
    "Light": "밝게",
    "Line number:": "줄 번호:",
    "Load AI review diff": "AI 리뷰 diff 로드",
    "Load Skill File...": "스킬 파일 로드...",
    "Load diff for history": "기록 diff 로드",
    "Load from File": "파일에서 로드",
    "Load revision headers": "리비전 헤더 로드",
    "Loaded skills:": "로드된 스킬:",
    "Loaded: {0}": "로드됨: {0}",
    "Loading": "로드 중",
    "Loading LFS files...": "LFS 파일 로드 중...",
    "Loading binary info for '{0}'": "'{0}'의 바이너리 정보 로드 중",
    "Loading changed files": "변경된 파일 로드 중",
    "Loading image content for '{0}'": "'{0}'의 이미지 내용 로드 중",
    "Loading repositories...": "저장소 로드 중...",
    "Loading submodule content for '{0}'": "'{0}'의 서브모듈 내용 로드 중",
    "Local Branch Selector": "로컬 브랜치 선택기",
    "Local Branch:": "로컬 브랜치:",
    "Local Changes": "로컬 변경사항",
    "Local branch:": "로컬 브랜치:",
    "Local changes:": "로컬 변경사항:",
    "Local only": "로컬만",
    "Location": "위치",
    "Location:": "위치:",
    "Lock": "잠금",
    "Locking '{0}'": "'{0}' 잠그는 중",
    "Locking {0} files": "{0}개 파일 잠그는 중",
    "Log In...": "로그인...",
    "Log Out": "로그아웃",
    "Log in": "로그인",
    "Log in to Bitbucket": "Bitbucket에 로그인",
    "Log in to Bitbucket Server": "Bitbucket Server에 로그인",
    "Log in to GitHub": "GitHub에 로그인",
    "Log in to GitHub Enterprise Server": "GitHub Enterprise Server에 로그인",
    "Log in to GitLab": "GitLab에 로그인",
    "Log in to Gitea server": "Gitea 서버에 로그인",
    "Log in to OpenAI": "OpenAI에 로그인",
    "Log in to {0}": "{0}에 로그인",
    "Log in to {0}...": "{0}에 로그인 중...",
    "Log out": "로그아웃",
    "Log out of {0}?": "{0}에서 로그아웃하시겠습니까?",
    "Logged in": "로그인됨",
    "Login to Bitbucket": "Bitbucket에 로그인",
    "Login to Bitbucket Server": "Bitbucket Server에 로그인",
    "Login to GitHub": "GitHub에 로그인",
    "Login to GitHub Enterprise Server": "GitHub Enterprise Server에 로그인",
    "Login to GitLab": "GitLab에 로그인",
    "Login to Gitea server": "Gitea 서버에 로그인",
    "Login to {0}": "{0}에 로그인",
    "Low limit:": "하한값:",
    "MacOS": "macOS",
    "Main Branch:": "메인 브랜치:",
    "Main repository": "메인 저장소",
    "Manage": "관리",
    "Manage ": "관리 ",
    "Manage git mm workspace and sub repositories": "git mm 워크스페이스 및 하위 저장소 관리",
    "Manifest Branch:": "매니페스트 브랜치:",
    "Manifest File:": "매니페스트 파일:",
    "Manifest Group:": "매니페스트 그룹:",
    "Manifest Repository Url:": "매니페스트 저장소 URL:",
    "Manifest URL:": "매니페스트 URL:",
    "Manifest branch": "매니페스트 브랜치",
    "Manifest branch:": "매니페스트 브랜치:",
    "Manifest file": "매니페스트 파일",
    "Manifest file:": "매니페스트 파일:",
    "Manifest group": "매니페스트 그룹",
    "Manifest group:": "매니페스트 그룹:",
    # <<<INSERT>>>
}

# Merge additional translations from translate_ko2.py
TRANS.update(TRANS2)

with open(ZH_PATH, 'r', encoding='utf-8-sig') as f:
    zh = json.load(f)
with open(KO_PATH, 'r', encoding='utf-8-sig') as f:
    ko = json.load(f)

existing = ko['translations']
final = {}
missing_from_trans = []
for k in zh['translations']:
    if k in existing:
        final[k] = existing[k]
    elif k in TRANS:
        final[k] = TRANS[k]
    else:
        final[k] = k
        missing_from_trans.append(k)

final_sorted = {k: final[k] for k in sorted(final.keys())}

out = {
    "code": "ko-KR",
    "name": "한국어",
    "translations": final_sorted
}

with open(KO_PATH, 'w', encoding='utf-8') as f:
    f.write('\ufeff')
    json.dump(out, f, ensure_ascii=False, indent=2)

print('total keys:', len(final_sorted))
print('missing from TRANS (fallback to english):', len(missing_from_trans))
for k in missing_from_trans:
    print('  MISSING:', repr(k))
