# -*- coding: utf-8 -*-
# Additional Korean translations for ForkPlus - Part 2
# These are merged with TRANS from translate_ko.py

TRANS2 = {
    "Source Code Folder": "소스 코드 폴더",
    "Show -+ marks": "-+ 표시",
    "Sort commits:": "커밋 정렬:",
    "Topologically": "위상순",
    "Tab indicator for uncommitted changes": "커밋되지 않은 변경사항 탭 표시기",
    "Update submodules automatically on checkout": "체크아웃 시 자동으로 서브모듈 업데이트",
    "Space character in branch names:": "브랜치명의 공백 문자:",
    "Push automatically on commit": "커밋 시 자동 푸시",
    "Spell checking:": "맞춤법 검사:",
    "System": "시스템",
    "Page guide at column:": "열 가이드 위치:",
    "OpenAI:": "OpenAI:",
    "Server Type:": "서버 유형:",
    "Status:": "상태:",
    "Update token...": "토큰 업데이트...",
    "Online": "온라인",
    "Unable to load repositories": "저장소를 불러올 수 없습니다",
    "You can always log back in at any time": "언제든지 다시 로그인할 수 있습니다",
    "Server:": "서버:",
    "Personal Access Token:": "개인 액세스 토큰:",
    "Username:": "사용자 이름:",
    "Open in separate window": "별도 창에서 열기",
    "Refreshing...": "새로고침 중...",
    "personal access tokens": "개인 액세스 토큰",
    "access tokens": "액세스 토큰",
    "Required scopes: read_user, read_api, read_repository, write_repository": "필수 스코프: read_user, read_api, read_repository, write_repository",
    "Required scopes:\n read:user:bitbucket\n read:repository:bitbucket\n read:workspace:bitbucket\n write:repository:bitbucket\n read:pullrequest:bitbucket": "필수 스코프:\n read:user:bitbucket\n read:repository:bitbucket\n read:workspace:bitbucket\n write:repository:bitbucket\n read:pullrequest:bitbucket",
    "Waiting for response from {0}...": "{0}의 응답을 기다리는 중...",
    "Waiting for reponse from {0}...": "{0}의 응답을 기다리는 중...",
    "You are already logged in to {0} as {1}": "이미 {1}로 {0}에 로그인되어 있습니다",
    "Select git instance": "Git 인스턴스 선택",
    "Shell": "Shell",
    "Shell:": "Shell:",
    "Shell Path:": "Shell 경로:",
    "primary": "기본",
    "Name:": "이름:",
    "Path:": "경로:",
    "Obsolete:": "사용 중단됨:",
    "repository name": "저장소 이름",
    "repository path": "저장소 경로",
    "revision sha": "리비전 SHA",
    "revision sha (abbreviated)": "리비전 SHA (약식)",
    "file path": "파일 경로",
    "file name": "파일 이름",
    "branch name": "브랜치 이름",
    "branch w/o remote prefix": "리모트 접두사 없는 브랜치",
    "branch full reference": "브랜치 전체 참조",
    "control variables": "컨트롤 변수",
    "string value": "문자열 값",
    "selected path": "선택된 경로",
    "last path component": "경로 마지막 부분",
    "commit sha": "커밋 SHA",
    "abbreviated commit sha": "커밋 SHA (약식)",
    "submodule": "서브모듈",
    "fork git instance": "Fork Git 인스턴스",
    "unix shell path": "Unix Shell 경로",
    "Use '/' for nesting": "'/'를 사용하여 그룹화",
    "Shared": "공유",
    "OS:": "운영체제:",
    "Windows": "Windows",
    "Target:": "대상:",
    "visible in commit context menu": "커밋 컨텍스트 메뉴에 표시",
    "visible in 'Open In' dropdown": "'연결 프로그램' 드롭다운에 표시",
    "visible in file context menu": "파일 컨텍스트 메뉴에 표시",
    "visible in branch context menu": "브랜치 컨텍스트 메뉴에 표시",
    "visible in submodule context menu": "서브모듈 컨텍스트 메뉴에 표시",
    "Remote branch": "리모트 브랜치",
    "Remote Branches": "리모트 브랜치",
    "Remote branch '{0}'": "리모트 브랜치 '{0}'",
    "e.g. '${repo:name}' status": "예: '${repo:name}' 상태",
    "UI": "UI",
    "Remote Branch Selector": "리모트 브랜치 선택기",
    "Tag Selector": "태그 선택기",
    "Reference Selector": "참조 선택기",
    "Text Box Type:": "텍스트 상자 유형:",
    "Path, e.g. 'src/*.js'": "경로, 예: 'src/*.js'",
    "Source code": "소스 코드",
    "{0} results": "{0}개 결과",
    "Title:": "제목:",
    "Text:": "텍스트:",
    "Placeholder:": "플레이스홀더:",
    "Placeholder Text (optional)": "플레이스홀더 텍스트 (선택)",
    "Save File": "파일 저장",
    "Open File": "파일 열기",
    "Open Directory": "디렉토리 열기",
    "Unchecked Value:": "미선택 값:",
    "Start Process": "프로세스 시작",
    "start application with parameters": "매개변수로 응용 프로그램 시작",
    "run bash script": "bash 스크립트 실행",
    "Open Url": "URL 열기",
    "open url in browser": "브라우저에서 URL 열기",
    "close dialog": "대화상자 닫기",
    "Url:": "URL:",
    "Script:": "스크립트:",
    "Parameters:": "매개변수:",
    "Wait for Exit": "종료 대기",
    "Wait for the process to exit": "프로세스 종료 대기",
    "Show the process output after it is finished": "프로세스 완료 후 출력 표시",
    "Select shell location": "Shell 위치 선택",
    "Wrap Paragraph at Ruler": "눈금선에서 문단 줄바꿈",
    "Resolved {0} conflicts of {1}": "{0}/{1}개 충돌 해결됨",
    "System ({0})": "시스템 ({0})",
    "Open '{0}' on {1} ({2})": "{1} ({2})에서 '{0}' 열기",
    "Old:\t{0}\nNew:\t{1}": "이전:\t{0}\n새:\t{1}",
    "Trust custom commands in '{0}'": "'{0}'의 사용자 정의 명령 신뢰",
    "Repository is in detached HEAD state": "저장소가 분리된 HEAD 상태입니다",
    "untracked files hidden": "추적 안 된 파일 숨김",
    "ignored files included": "무시된 파일 포함됨",
    "Open a repository to start": "저장소를 열어 시작하세요",
    "loading...": "로딩 중...",
    "detached HEAD": "분리된 HEAD",
    "Submodule '{0}' changed": "서브모듈 '{0}'이(가) 변경됨",
    "Not available": "사용할 수 없음",
    "Revision Details": "리비전 정보",
    "We need to update the Fork git instance to 2.50.1": "Fork 내장 Git을 2.50.1로 업데이트해야 합니다",
    "This will take a few minutes": "몇 분 정도 소요됩니다",
    "Updating Fork internal git instance...": "Fork 내장 Git 업데이트 중...",
    "Removing the old Fork git instance...": "이전 Fork 내장 Git 제거 중...",
    "Remove Right": "오른쪽 제거",
    "Select Right": "오른쪽 선택",
    "Remove Left": "왼쪽 제거",
    "Select Left": "왼쪽 선택",
    "Select location": "위치 선택",
    "Select Location": "위치 선택",
    "Select repository": "저장소 선택",
    "Select external tool": "외부 도구 선택",
    "Select File": "파일 선택",
    "Select patch": "패치 선택",
    "Save file": "파일 저장",
    "Open file": "파일 열기",
    "Open directory": "디렉토리 열기",
    "Patches": "패치",
    "Select SSH key": "SSH 키 선택",
    "SSH key": "SSH 키",
    "User name": "사용자 이름",
    "Updating...": "업데이트 중...",
    "Move to:": "이동할 위치:",
    "Reset type:": "재설정 유형:",
    "Soft": "소프트",
    "Mixed": "믹스드",
    "Remote branch:": "리모트 브랜치:",
    "New Name:": "새 이름:",
    "Stash and reapply": "스태시 후 재적용",
    "Stop if some local changes would be overwritten by checkout": "체크아웃이 로컬 변경사항을 덮어쓰면 중지",
    "Rebase:": "리베이스:",
    "On:": "대상:",
    "Update dependent branches": "종속 브랜치 업데이트",
    "Stash and reapply local changes": "로컬 변경사항을 스태시 후 재적용",
    "Tag:": "태그:",
    "Tags:": "태그:",
    "Remote:": "리모트:",
    "Merge:": "병합:",
    "Merge Option:": "병합 옵션:",
    "Start from:": "시작 위치:",
    "Start branch on:": "브랜치 시작 기준:",
    "Tracked branch:": "추적 브랜치:",
    "[removed]": "[제거됨]",
    "Tag Name:": "태그 이름:",
    "Message:": "메시지:",
    "Push to all remotes": "모든 리모트에 푸시",
    "Tag '{0}' already exists": "태그 '{0}'이(가) 이미 존재합니다",
    "Pushing '{0}' to '{1}'...": "'{0}'을(를) '{1}'에 푸시 중...",
    "Worktree '{0}' already exists": "워크트리 '{0}'이(가) 이미 존재합니다",
    "Switch to another branch": "다른 브랜치로 전환",
    "Tracking '{0}'...": "'{0}' 추적 중...",
    "No tracking": "추적 안 함",
    "Remove tracking reference": "추적 참조 제거",
    "Update tracking reference": "추적 참조 업데이트",
    "Removing tracking reference...": "추적 참조 제거 중...",
    "Remote Branch Name": "리모트 브랜치 이름",
    "Reset '{0}' ({1})": "'{0}' 재설정 ({1})",
    "Rebase '{0}' onto '{1}'": "'{0}'을(를) '{1}'에 리베이스",
    "Merge '{0}' into '{1}'": "'{0}'을(를) '{1}'에 병합",
    "Start '{0}'": "'{0}' 시작",
    "Refresh working directory": "작업 디렉토리 새로고침",
    "Select version to resolve with": "해결에 사용할 버전 선택",
    "Merge Branch": "브랜치 병합",
    "Push Tag": "태그 푸시",
    "Push {0} tags": "{0}개 태그 푸시",
    "Push {0} branches": "{0}개 브랜치 푸시",
    "Rename Local Branch": "로컬 브랜치 이름 변경",
    "Track Remote Branch": "리모트 브랜치 추적",
    "Track": "추적",
    "Reset Current Branch to Revision": "현재 브랜치를 리비전으로 재설정",
    "Reset HEAD to Revision": "HEAD를 리비전으로 재설정",
    "Start Branch on '{0}'...": "'{0}'에서 브랜치 시작...",
    "Sync (Rebase on '{0}')": "동기화 ('{0}'에 리베이스)",
    "Sync '{0}' (Rebase on '{1}')": "'{0}' 동기화 ('{1}'에 리베이스)",
    "Sync '{0}' with '{1}'": "'{0}'을(를) '{1}'과(와) 동기화",
    "Use '/' as a path separator to create folders": "'/'를 경로 구분자로 사용하여 폴더 생성",
    "You must sync '{0}' first": "먼저 '{0}'을(를) 동기화해야 합니다",
    "You must checkout and sync '{0}' first": "먼저 '{0}'을(를) 체크아웃하고 동기화해야 합니다",
    "You must sync '{0}' with '{1}' first": "먼저 '{0}'을(를) '{1}'과(와) 동기화해야 합니다",
    "Merging into '{0}'...": "'{0}'에 병합 중...",
    "Welcome to Fork": "ForkPlus에 오신 것을 환영합니다",
    "User Information": "사용자 정보",
    "User information": "사용자 정보",
    "Set up your user name and email address. This information will be associated with your Git commits.": "사용자 이름과 이메일 주소를 설정하세요. 이 정보는 Git 커밋에 연결됩니다.",
    "User name:": "사용자 이름:",
    "email@domain.com (optional)": "email@domain.com (선택)",
    "Preparing Fork for the first run...": "Fork 첫 실행 준비 중...",
    "_File": "파일(_F)",
    "_View": "보기(_V)",
    "_Repository": "저장소(_R)",
    "_Window": "창(_W)",
    "_Help": "도움말(_H)",
    "View": "보기",
    "Window": "창",
    "Quick Launch": "빠른 실행",
    "Quick Launch...": "빠른 실행...",
    "Recent Repositories": "최근 저장소",
    "Switch Workspace": "워크스페이스 전환",
    "Zoom In": "확대",
    "Zoom Out": "축소",
    "start": "시작",
    "skip": "건너뛰기",
    "reset": "재설정",
    "bad": "나쁨",
    "good": "좋음",
    "Merging branch '": "브랜치 병합 중 '",
    "Rebasing '": "리베이스 중 '",
    "Reverting commit '": "커밋 되돌리는 중 '",
    "Squashing commits": "커밋 압축 중",
    "Squashing commits. Fix {0} {1} and continue.": "커밋 압축 중. {0}개 {1}을(를) 해결하고 계속하세요.",
    "Working directory contains {0} unmerged {1}.": "작업 디렉토리에 {0}개의 병합되지 않은 {1}이(가) 있습니다.",
    "conflict": "충돌",
    "conflicts": "충돌",
    "file": "파일",
    "files": "파일",
    "{0} file...": "{0}개 파일...",
    "{0} files...": "{0}개 파일...",
    "{0} uncommitted file": "{0}개 미커밋 파일",
    "{0} uncommitted files": "{0}개 미커밋 파일",
    "Skip": "건너뛰기",
    "Resolve": "해결",
    "Repository Settings...": "저장소 설정...",
    "Repository Statistics...": "저장소 통계...",
    "Repository Treemap...": "저장소 트리맵...",
    "Repository Treemap": "저장소 트리맵",
    "{0} - Repository Overview": "{0} - 저장소 개요",
    "Read repository overview": "저장소 개요 읽기",
    "{0} commits": "{0}개 커밋",
    "{0} commits...": "{0}개 커밋...",
    "Merge...": "병합...",
    "Rebase...": "리베이스...",
    "Rename Branch...": "브랜치 이름 변경...",
    "Timeline": "타임라인",
    "Merge Conflict": "병합 충돌",
    "fatal: There is no path '{0}' in the commit": "fatal: 커밋에 경로 '{0}'이(가) 없습니다",
    "Remove .git/index.lock": ".git/index.lock 제거",
    "Mark repository as safe": "저장소를 안전으로 표시",
    "Merge unrelated history": "관련 없는 기록 병합",
    "Skip pre-commit hooks and commit": "pre-commit 훅 건너뛰고 커밋",
    "Merge unrelated '{0}'": "관련 없는 '{0}' 병합",
    "Save as Patch…": "패치로 저장…",
    "Save as Patch...": "패치로 저장...",
    "Save patch as...": "패치를 다른 이름으로 저장...",
    "Save commit as patch": "커밋을 패치로 저장",
    "Revision:": "리비전:",
    "Revisions:": "리비전:",
    "Select patch to apply": "적용할 패치 선택",
    "Patch can be applied without conflicts": "패치를 충돌 없이 적용할 수 있습니다",
    "Patch will cause conflicts": "패치로 인해 충돌이 발생합니다",
    "Open In {0}": "{0}에서 열기",
    "Open In Console": "콘솔에서 열기",
    "Open in Console": "콘솔에서 열기",
    "Unlock": "잠금 해제",
    "Refreshing LFS locks...": "LFS 잠금 새로고침 중...",
    "Unlocking '{0}'": "'{0}' 잠금 해제 중",
    "Unlocking {0} files": "{0}개 파일 잠금 해제 중",
    "tag": "태그",
    "branch": "브랜치",
    "remote branch": "리모트 브랜치",
    "branch or tag": "브랜치 또는 태그",
    "feature branch": "기능 브랜치",
    "hotfix branch": "핫픽스 브랜치",
    "release branch": "릴리스 브랜치",
    "remote": "리모트",
    "workspace": "워크스페이스",
    "branch to rename": "이름을 변경할 브랜치",
    "branch to delete": "삭제할 브랜치",
    "tag to delete": "삭제할 태그",
    "Pulling...": "풀 중...",
    "Pulling LFS files...": "LFS 파일 풀 중...",
    "Pushing...": "푸시 중...",
    "Pulled '{0}'": "'{0}' 풀 완료",
    "Workspaces": "워크스페이스",
    "Work": "작업",
    "New Workspace": "새 워크스페이스",
    "Use '/' as path separator to create folders": "'/'를 경로 구분자로 사용하여 폴더 생성",
    "Show workspace name in title bar": "제목 표시줄에 워크스페이스 이름 표시",
    "Pin": "고정",
    "Show": "표시",
    "Show all local branches ({0})": "모든 로컬 브랜치 표시 ({0})",
    "Show all tags ({0})": "모든 태그 표시 ({0})",
    "Show all stashes ({0})": "모든 스태시 표시 ({0})",
    "Show less": "간단히 표시",
    "You can't undo this action": "이 작업은 되돌릴 수 없습니다",
    "Open in": "연결 프로그램",
    "git mm": "git mm",
    "Open git mm": "git mm 열기",
    "Refresh Children": "하위 항목 새로고침",
    "Open Folder": "폴더 열기",
    "Remove Workspace": "워크스페이스 제거",
    "Select Workspace": "워크스페이스 선택",
    "Select workspace": "워크스페이스 선택",
    "git mm Workspaces": "git mm 워크스페이스",
    "Manifest repository URL": "매니페스트 저장소 URL",
    "Sub repositories": "하위 저장소",
    "[Main]": "[메인]",
    "[Sub]": "[하위]",
    "Operation Area": "작업 영역",
    "{0}/{1} selected": "{0}/{1} 선택됨",
    "{0}/{1} shown": "{0}/{1} 표시됨",
    "Search repositories": "저장소 검색",
    "Show all repositories": "모든 저장소 표시",
    "Non-default branch": "비기본 브랜치",
    "Non-default: {0}": "비기본: {0}",
    "Up to date with '{0}'": "'{0}'과(와) 최신 상태",
    "Switched to branch '{0}'": "브랜치 '{0}'(으)로 전환됨",
    "Select all repositories": "모든 저장소 선택",
    "Start git mm": "git mm 시작",
    "Start development branch for git mm sub repositories": "git mm 하위 저장소의 개발 브랜치 시작",
    "Sub repositories:": "하위 저장소:",
    "_All sub repositories": "모든 하위 저장소(_A)",
    "Select sub repositories": "하위 저장소 선택",
    "Start from HEAD": "HEAD에서 시작",
    "Search mode:": "검색 모드:",
    "Sync git mm": "git mm 동기화",
    "Sync git mm workspace": "git mm 워크스페이스 동기화",
    "Workspace:": "워크스페이스:",
    "Network only": "네트워크만",
    "Remove dirty projects": "변경된 프로젝트 제거",
    "Upload git mm": "git mm 업로드",
    "Upload git mm changes for review": "리뷰를 위해 git mm 변경사항 업로드",
    "Topic:": "주제:",
    "Topic": "주제",
    "Reviewers:": "리뷰어:",
    "Upload HEAD": "HEAD 업로드",
    "Ready": "준비 완료",
    "Work in progress": "작업 진행 중",
    "No update manifest": "매니페스트 업데이트 안 함",
    "_Force upload": "강제 업로드(_F)",
    "_Force sync": "강제 동기화(_F)",
    "Update manifest": "매니페스트 업데이트",
    "Open a repository first": "먼저 저장소를 여세요",
    "Scanning git mm sub repositories...": "git mm 하위 저장소 스캔 중...",
    "{0} repositories": "{0}개 저장소",
    "{0} sub repositories": "{0}개 하위 저장소",
    "git mm command finished": "git mm 명령 완료",
    "git mm command finished with errors": "git mm 명령이 오류와 함께 완료됨",
    "No command history": "명령 기록 없음",
    "Uploads": "업로드 결과",
    "Recent Uploads:": "최근 업로드:",
    "git mm upload opened in terminal": "터미널에서 git mm upload가 열렸습니다",
    "No Activities": "활동 없음",
    "No Selected Activity": "선택된 활동 없음",
    "User": "사용자",
    "running": "실행 중",
    "canceling...": "취소 중...",
    "canceled": "취소됨",
    "succeeded": "성공",
    "Repository Settings": "저장소 설정",
    "Use global git credentials": "전역 Git 자격 증명 사용",
    "No fast-forward on merge": "병합 시 패스트포워드 안 함",
    "Tab Width:": "탭 너비:",
    "Use global git configuration file": "전역 Git 설정 파일 사용",
    "Rule name": "규칙 이름",
    "Parsing Regular Expression:": "정규식 파싱:",
    "Result Url:": "결과 URL:",
    "Test Message:": "테스트 메시지:",
    "Test commit message": "테스트 커밋 메시지",
    "valid": "유효",
    "invalid": "무효",
    "default ({0})": "기본값 ({0})",
    "default (develop, main or master)": "기본값 (develop, main 또는 master)",
    "Search Commits": "커밋 검색",
    "Pull Requests": "풀 리퀘스트",
    "Stashes": "스태시",
    "Worktrees": "워크트리",
    "Repository URL:": "저장소 URL:",
    "Relative Local Path": "상대 로컬 경로",
    "Open Submodule In New Tab": "새 탭에서 서브모듈 열기",
    "Update '{0}'": "'{0}' 업데이트",
    "Updated '{0}'": "'{0}' 업데이트됨",
    "Update Submodules": "서브모듈 업데이트",
    "Update {0} submodules": "{0}개 서브모듈 업데이트",
    "Updating submodule": "서브모듈 업데이트 중",
    "Updating {0} submodules": "{0}개 서브모듈 업데이트 중",
    "{0} submodules": "{0}개 서브모듈",
    "Move '{0}'...": "'{0}' 이동...",
    "Moving '{0}'": "'{0}' 이동 중",
    "Select empty folder for new submodule location": "새 서브모듈 위치를 위한 빈 폴더 선택",
    "Show in File Tree": "파일 트리에서 표시",
    "Show In File Tree": "파일 트리에서 표시",
    "REFS": "참조",
    "SHA": "SHA",
    "PARENTS": "부모",
    "See full list of changed files ({0}) in the Changes tab": "변경 탭에서 전체 변경 파일 목록({0}) 보기",
    "Show All Commits": "모든 커밋 표시",
    "Reflog mode enabled": "Reflog 모드 활성화됨",
    "View Mode": "보기 모드",
    "Show diff side-by-side (space bar)": "나란히 diff 표시 (스페이스바)",
    "Show hidden symbols": "숨겨진 기호 표시",
    "Word wrap": "자동 줄바꿈",
    "Show entire file": "전체 파일 표시",
    "Split diff": "분할 diff",
    "Side by side diff": "나란히 diff",
    "Recent Commit Messages": "최근 커밋 메시지",
    "Stage {0} File": "{0}개 파일 스테이지",
    "Stage {0} Files": "{0}개 파일 스테이지",
    "Unstage {0} File": "{0}개 파일 스테이지 해제",
    "Unstage {0} Files": "{0}개 파일 스테이지 해제",
    "Open All": "모두 열기",
    "New Tab": "새 탭",
    "Open Repository...": "저장소 열기...",
    "Repository Url:": "저장소 URL:",
    "Parent Folder:": "상위 폴더:",
    "Parent folder path": "상위 폴더 경로",
    "Repository name": "저장소 이름",
    "git mm init failed": "git mm init 실패",
    "Test Connection": "연결 테스트",
    "SSH configuration:": "SSH 설정:",
    "No SSH keys": "SSH 키 없음",
    "New SSH Key...": "새 SSH 키...",
    "Open Existing SSH Key...": "기존 SSH 키 열기...",
    "Public Key:": "공개 키:",
    "default system ssh-agent": "기본 시스템 ssh-agent",
    "Note: you can't use multiple SSH keys with the same server": "참고: 동일한 서버에 여러 SSH 키를 사용할 수 없습니다",
    "Ssh key '{0}' already exists": "SSH 키 '{0}'이(가) 이미 존재합니다",
    "Passphrase:": "패스프레이즈:",
    "User Name:": "사용자 이름:",
    "Password:": "비밀번호:",
    "Passphrase for SSH key '{0}'": "SSH 키 '{0}'의 패스프레이즈",
    "Passphrase for '{0}'": "'{0}'의 패스프레이즈",
    "Passphrase for SSH key": "SSH 키 패스프레이즈",
    "default": "기본",
    "custom": "사용자 정의",
    "Permission denied (publickey)": "권한 거부됨 (publickey)",
    "Repository not found": "저장소를 찾을 수 없음",
    "Preferences...": "환경설정...",
    "Open In File Explorer": "파일 탐색기에서 열기",
    "Open In External Editor": "외부 편집기에서 열기",
    "Open Git Bash": "Git Bash 열기",
    "Pull...": "풀...",
    "Push...": "푸시...",
    "Save Stash...": "스태시 저장...",
    "New Branch...": "새 브랜치...",
    "New Tag...": "새 태그...",
    "Version {0}": "버전 {0}",
    "Repository Manager": "저장소 관리자",
    "Recent": "최근",
    "Uncommitted Files:": "미커밋 파일:",
    "Remotes:": "리모트:",
    "Summary": "요약",
    "Statistics": "통계",
    "Top contributors": "주요 기여자",
    "Unable to generate statistics": "통계를 생성할 수 없습니다",
    "Mon": "월",
    "Tue": "화",
    "Wed": "수",
    "Thu": "목",
    "Sat": "토",
    "Sun": "일",
    "Repository Not Found": "저장소를 찾을 수 없음",
    "Repository was deleted or moved. Do you want to remove the reference from Fork?": "저장소가 삭제되었거나 이동되었습니다. Fork에서 참조를 제거하시겠습니까?",
    "Repository is located at the place owned by someone else": "저장소가 다른 사용자가 소유한 위치에 있습니다",
    "Repository is unsafe and owned by someone else. Is it safe?": "저장소가 안전하지 않으며 다른 사용자가 소유하고 있습니다. 안전합니까?",
    "Mark it as safe": "안전으로 표시",
    "{0} is located in directory owned by someone else": "{0}이(가) 다른 사용자가 소유한 디렉토리에 있습니다",
    "Mark {0} as safe": "{0}을(를) 안전으로 표시",
    "Open All ({0})": "모두 열기 ({0})",
    "Rescan Repositories...": "저장소 다시 스캔...",
    "Remove...": "제거...",
    "Validating repository path...": "저장소 경로 검증 중...",
    "The repository will remain on disk": "저장소는 디스크에 유지됩니다",
    "The repositories will remain on disk": "저장소는 디스크에 유지됩니다",
    "Reset File to Unmerged State...": "파일을 병합되지 않은 상태로 재설정...",
    "Reset File to Unmerged state": "파일을 병합되지 않은 상태로 재설정",
    "This will reset conflict resolution and return the file to the unmerged state.": "충돌 해결 결과가 재설정되고 파일이 병합되지 않은 상태로 되돌아갑니다.",
    "Unmerge": "병합 취소",
    "Undo the rebase and check out the original branch?": "리베이스를 취소하고 원래 브랜치를 체크아웃하시겠습니까?",
    "The current file changes will be discarded.": "현재 파일 변경사항이 폐기됩니다.",
    "Show Changes view (second press will focus commit field)": "변경사항 보기 표시 (두 번째 누르면 커밋 입력란에 포커스)",
    "Show All Commits view (second press will jump to HEAD)": "모든 커밋 보기 표시 (두 번째 누르면 HEAD로 이동)",
    "Reveal HEAD": "HEAD 표시",
    "Show Quick Launch window": "빠른 실행 창 표시",
    "Select next tab": "다음 탭 선택",
    "Select previous tab": "이전 탭 선택",
    "Open new tab": "새 탭 열기",
    "Zoom in / Zoom out": "확대 / 축소",
    "Open ForkPlus preferences": "ForkPlus 환경설정 열기",
    "Remove branch/stash": "브랜치/스태시 삭제",
    "Run prepare-commit-msg hook": "prepare-commit-msg 훅 실행",
    "Stage/unstage selected file (or lines)": "선택한 파일(또는 라인) 스테이지/스테이지 해제",
    "Stage/unstage all files": "모든 파일 스테이지/스테이지 해제",
    "Open selected file": "선택한 파일 열기",
    "Open selected file in external diff tool": "선택한 파일을 외부 diff 도구로 열기",
    "Open Repository": "저장소 열기",
    "Open repository": "저장소 열기",
    "Quick Fetch": "빠른 페치",
    "Quick Pull": "빠른 풀",
    "Quick Push": "빠른 푸시",
    "New branch": "새 브랜치",
    "New tag": "새 태그",
    "Open in File Explorer": "파일 탐색기에서 열기",
    "Open in Terminal": "터미널에서 열기",
    "Remove Repository": "저장소 제거",
    "Visit Fork Website": "Fork 웹사이트 방문",
    "Open @git_fork on Twitter": "Twitter에서 @git_fork 열기",
    "Theme": "테마",
    "Vertical": "세로",
    "Select Stale Local Branches": "오래된 로컬 브랜치 선택",
    "Sort Branches:": "브랜치 정렬:",
    "Sort Tags:": "태그 정렬:",
    "Recently used": "최근 사용",
    "Tracking": "추적",
    "Rename Repository": "저장소 이름 변경",
    "Rename Repository...": "저장소 이름 변경...",
    "View as Tree": "트리 보기",
    "View as List": "목록 보기",
    "View as Combined List": "결합 목록 보기",
    "Show Ignored Files": "무시된 파일 표시",
    "Reveal in Fork": "Fork에서 표시",
    "Reveal Line in": "라인 표시",
    "Reveal Line in {0}": "{0}에서 라인 표시",
    "No newline at end of file": "파일 끝에 줄바꿈 없음",
    "created": "생성됨",
    "removed": "제거됨",
    "old": "이전",
    "new": "새",
    "Save As...": "다른 이름으로 저장...",
    "Smudge LFS image": "LFS 이미지 스머지",
    "Paste": "붙여넣기",
    "Pattern:": "패턴:",
    "Preview:": "미리보기:",
    "{0} files match": "{0}개 파일 일치",
    "Primary": "기본",
    "Visible": "표시",
    "Reset to default": "기본값으로 재설정",
    "Rename...": "이름 변경...",
    "Rename local branch": "로컬 브랜치 이름 변경",
    "Renaming can break tracking references for other users": "이름 변경은 다른 사용자의 추적 참조를 손상할 수 있습니다",
    "Renaming branch...": "브랜치 이름 변경 중...",
    "Rename branch '{0}'": "브랜치 '{0}' 이름 변경",
    "Renaming remote branch...": "리모트 브랜치 이름 변경 중...",
    "Updating tracking reference...": "추적 참조 업데이트 중...",
    "Show Uncommitted Changes": "미커밋 변경사항 표시",
    "Show HEAD": "HEAD 표시",
    "Show Lost Commits (Reflog)": "잃어버린 커밋 표시 (Reflog)",
    "Select Previous Tab": "이전 탭 선택",
    "Select Next Tab": "다음 탭 선택",
    "Switch Theme": "테마 전환",
    "Settings for This Repository...": "이 저장소 설정...",
    "New Worktree...": "새 워크트리...",
    "Performance Benchmark...": "성능 벤치마크...",
    "Performance Benchmark": "성능 벤치마크",
    "Measure repository performance": "저장소 성능 측정",
    "System latency": "시스템 지연",
    "Reading changed files": "변경된 파일 읽기",
    "Reading branches and tags": "브랜치와 태그 읽기",
    "Reading commits": "커밋 읽기",
    "Reading commits bt": "커밋 읽기 (bt)",
    "Measuring system latency": "시스템 지연 측정",
    "SCORE": "점수",
    "{0} {1:0.}%...": "{0} {1:0.}%...",
    "Score: {0:0.0}": "점수: {0:0.0}",
    "Status...": "상태...",
    "Status (Locks)...": "상태 (잠금)...",
    "Prune": "정리",
    "Start using Git Flow by initializing it inside an existing git repository": "기존 Git 저장소에서 Git Flow를 초기화하여 시작",
    "Production Branch:": "프로덕션 브랜치:",
    "Release Prefix:": "릴리스 접두사:",
    "Version Tag Prefix:": "버전 태그 접두사:",
    "Production branch name can't be empty": "프로덕션 브랜치 이름은 비울 수 없습니다",
    "Release branch prefix can't be empty": "릴리스 브랜치 접두사는 비울 수 없습니다",
    "Start Feature...": "기능 시작...",
    "Start Release...": "릴리스 시작...",
    "Start Hotfix...": "핫픽스 시작...",
    "Open Application Data Folder": "응용 프로그램 데이터 폴더 열기",
    "Trace Elapsed Time": "경과 시간 추적",
    "Repository Files": "저장소 파일",
    "Pinned": "고정됨",
    "Search '{0}'": "'{0}' 검색",
    "Revision details": "리비전 정보",
    "Refresh Repository": "저장소 새로고침",
    "Refresh Notifications": "알림 새로고침",
    "Signing in...": "로그인 중...",
    "Test connection": "연결 테스트",
    "fetch until shas": "SHA까지 페치",
    "fetch next page": "다음 페이지 페치",
    "fetch until search match": "검색 일치까지 페치",
    "Recent Queries": "최근 쿼리",
    "My Pull Requests": "내 풀 리퀘스트",
    "My Issues": "내 이슈",
    "Open '{0}'...": "'{0}' 열기...",
    "Rename '{0}'...": "'{0}' 이름 변경...",
    "Merge into '{0}'...": "'{0}'에 병합...",
    "Merge '{0}' into {1}...": "'{0}'을(를) {1}에 병합...",
    "Rebase '{0}' on '{1}'...": "'{0}'을(를) '{1}'에 리베이스...",
    "Push '{0}' to '{1}'...": "'{0}'을(를) '{1}'에 푸시...",
    "Push {0} branches to '{1}'...": "{0}개 브랜치를 '{1}'에 푸시...",
    "Push {0} branches to": "{0}개 브랜치를 다음에 푸시:",
    "Push {0} tags to '{1}'...": "{0}개 태그를 '{1}'에 푸시...",
    "Push {0} tags to": "{0}개 태그를 다음에 푸시:",
    "Open {0} submodules": "{0}개 서브모듈 열기",
    "Open {0} worktrees...": "{0}개 워크트리 열기...",
    "Stash {0} File...": "{0}개 파일 스태시...",
    "Stash {0} Files...": "{0}개 파일 스태시...",
    "Stash {0} {1}...": "{0}개 {1} 스태시...",
    "Track All Files in '{0}'...": "'{0}'의 모든 파일 추적...",
    "Track All Files": "모든 파일 추적",
    "Track All Files...": "모든 파일 추적...",
    "Track '{0}'": "'{0}' 추적",
    "Track All {0} Files...": "모든 {0} 파일 추적...",
    "Merge in {0}": "{0}에서 병합",
    "Open in {0}": "{0}에서 열기",
    "Open '{0}' in {1}": "'{0}'을(를) {1}에서 열기",
    "Push and Create Pull Request on '{0}'...": "푸시하고 '{0}'에 풀 리퀘스트 생성...",
    "View on {0}": "{0}에서 보기",
    "Pull '{0}' into '{1}'...": "'{0}'을(를) '{1}'에 풀...",
    "Pull '{0}'": "'{0}' 풀",
    "Pull '{0}'...": "'{0}' 풀...",
    "Resolve Using '{0}'": "'{0}'을(를) 사용하여 해결",
    "Save Commit Range as Patch…": "커밋 범위를 패치로 저장…",
    "Parent to skip:": "건너뛸 부모:",
    "Quick Actions": "빠른 작업",
    "Pick": "선택",
    "Use Commit": "커밋 사용",
    "Stop for amending": "수정을 위해 중지",
    "Reword": "설명 수정",
    "Squash": "압축",
    "Meld commit into previous one and keep message": "이전 커밋에 병합하고 메시지 유지",
    "Meld commit into previous one and discard message": "이전 커밋에 병합하고 메시지 폐기",
    "Remove commit": "커밋 제거",
    "Move up": "위로 이동",
    "Move Up": "위로 이동",
    "Move Down": "아래로 이동",
    "Reword...": "설명 수정...",
    "Reword…": "설명 수정…",
    "Revert Commit...": "커밋 되돌리기...",
    "Revert changes of the individual commit": "개별 커밋의 변경사항 되돌리기",
    "Revert '{0}'": "'{0}' 되돌리기",
    "Reverting...": "되돌리는 중...",
    "Squash into Parent": "부모에 압축",
    "Squash into Parent...": "부모에 압축...",
    "Squash into Parent…": "부모에 압축…",
    "Reset '{0}' to Here...": "'{0}'을(를) 여기로 재설정...",
    "Rebase '{0}' to Here...": "'{0}'을(를) 여기로 리베이스...",
    "State At Commit...": "커밋 시점 상태...",
    "State at Commit...": "커밋 시점 상태...",
    "State at Commit '{0}'...": "커밋 '{0}' 시점 상태...",
    "State Before Commit...": "커밋 이전 상태...",
    "Open in Separate Window...": "별도 창에서 열기...",
    "Reset File to State at Commit...": "파일을 커밋 시점 상태로 재설정...",
    "Reset File to": "파일 재설정:",
    "Reset {0} Files to": "{0}개 파일 재설정:",
    "Show in File Explorer": "파일 탐색기에서 표시",
    "Save as...": "다른 이름으로 저장...",
    "Reset File To": "파일 재설정:",
    "Reset File": "파일 재설정",
    "Reset Files": "파일 재설정",
    "Show '{0}' Details...": "'{0}' 정보 표시...",
    "Push to '{0}'...": "'{0}'에 푸시...",
    "Pull remote branches and merge them into your local branch": "리모트 브랜치를 풀하여 로컬 브랜치에 병합",
    "Rebase instead of merge": "병합 대신 리베이스",
    "Updating submodules...": "서브모듈 업데이트 중...",
    "Pull failed": "풀 실패",
    "Update submodules failed": "서브모듈 업데이트 실패",
    "Push your local changes to remote repository": "로컬 변경사항을 리모트 저장소에 푸시",
    "To:": "대상:",
    "Push all tags": "모든 태그 푸시",
    "_Force push": "강제 푸시(_F)",
    "new ({0})": "새로운 ({0})",
    "{0} (new)": "{0} (새로운)",
    "Unpushed submodules check": "미푸시 서브모듈 확인",
    "Submodule '{0}' contains unpushed changes": "서브모듈 '{0}'에 미푸시 변경사항이 있습니다",
    "Push '{0}' to '{1}'": "'{0}'을(를) '{1}'에 푸시",
    "Push {0} branches to '{1}'": "{0}개 브랜치를 '{1}'에 푸시",
    "Push {0} tags to '{1}'": "{0}개 태그를 '{1}'에 푸시",
    "Overwrite the remote branch even if it's not an ancestor of the local branch.\n- Force push is required for rebase of already published branch.\n- Blindly using force push can be dangerous as you can overwrite other users' commits.\n- Fork always uses --force-with-lease which protects from race conditions.": "리모트 브랜치가 로컬 브랜치의 조상이 아니더라도 덮어씁니다.\n- 이미 게시된 브랜치를 리베이스하려면 강제 푸시가 필요합니다.\n- 무작정 강제 푸시를 사용하면 다른 사용자의 커밋을 덮어쓸 수 있어 위험합니다.\n- Fork는 항상 --force-with-lease를 사용하여 경쟁 조건을 방지합니다.",
    "Push tag to remote repository": "태그를 리모트 저장소에 푸시",
    "Push {0} tags to remote repository": "{0}개 태그를 리모트 저장소에 푸시",
    "Push {0} branches to remote repository": "{0}개 브랜치를 리모트 저장소에 푸시",
    "Save stash": "스태시 저장",
    "Save Stash": "스태시 저장",
    "Save snapshot": "스냅샷 저장",
    "Save Snapshot": "스냅샷 저장",
    "Save Snapshot...": "스냅샷 저장...",
    "Recent Stashes": "최근 스태시",
    "Save your local changes to a new stash": "로컬 변경사항을 새 스태시에 저장",
    "Save your local changes to a new stash, but keep them in the working directory": "로컬 변경사항을 새 스태시에 저장하지만 작업 디렉토리에 유지",
    "Save your local modifications to a new stash. BOTH staged and unstaged changes will be stashed": "로컬 수정사항을 새 스태시에 저장합니다. 스테이지된 변경사항과 스테이지되지 않은 변경사항 모두 스태시됩니다",
    "Stash message (optional)": "스태시 메시지 (선택)",
    "Stage new files": "새 파일 스테이지",
    "Stash local changes": "로컬 변경사항 스태시",
    "Stash snapshot": "스태시 스냅샷",
    "Partial stash": "부분 스태시",
    "Stash Files...": "파일 스태시...",
    "Stash to Apply:": "적용할 스태시:",
    "Stash will not be deleted if a conflict occurs": "충돌이 발생하면 스태시가 삭제되지 않습니다",
    "Rename Stash": "스태시 이름 변경",
    "Rename Stash...": "스태시 이름 변경...",
    "Update stash message": "스태시 메시지 업데이트",
    "Updating message...": "메시지 업데이트 중...",
    "Rename stash '{0}'": "스태시 '{0}' 이름 변경",
    "Stash:": "스태시:",
    "Stashes:": "스태시:",
    "Welcome to ForkPlus!": "ForkPlus에 오신 것을 환영합니다!",
    "Merge conflict": "병합 충돌",
    "Select the changes or merge them manually": "변경사항을 선택하거나 수동으로 병합",
    "You can stage the file now.": "지금 파일을 스테이지할 수 있습니다.",
    "Merge branch into another one": "브랜치를 다른 브랜치에 병합",
    "No fast-forward": "패스트포워드 안 함",
    "Rebase before merging": "병합 전 리베이스",
    "Release Name": "릴리스 이름",
    "Release:": "릴리스:",
    "Start at:": "시작 위치:",
    "Start Feature": "기능 시작",
    "Start Git Flow feature": "Git Flow 기능 시작",
    "Start Git Flow hotfix": "Git Flow 핫픽스 시작",
    "Start Git Flow release": "Git Flow 릴리스 시작",
    "Start Hotfix": "핫픽스 시작",
    "Start Release": "릴리스 시작",
    "Switch to:": "전환:",
    "Move HEAD to the selected revision": "HEAD를 선택한 리비전으로 이동",
    "Reset previously deleted repository entries": "이전에 삭제된 저장소 항목 재설정",
    "Token with 'api write_repository' scopes": "'api write_repository' 스코프가 있는 토큰",
    "Token with 'read user, read and write repository' scopes": "'read user, read and write repository' 스코프가 있는 토큰",
    "Remember in Credential Manager": "자격 증명 관리자에 기억",
    "Remember in Windows Credential Manager": "Windows 자격 증명 관리자에 기억",
    "Remote name": "리모트 이름",
    "Track:": "추적:",
    "Sync submodule URL with parent repository": "서브모듈 URL을 부모 저장소와 동기화",
    "Select two commits to see difference between them": "두 커밋 간의 차이를 보려면 두 커밋을 선택하세요",
    "Search SHA, branch, author or message": "SHA, 브랜치, 작성자 또는 메시지 검색",
    "Space bar: close, Up/Down: move file selection": "스페이스바: 닫기, 위/아래: 파일 선택 이동",
    "Switch orientation": "방향 전환",
    "Resolved": "해결됨",
    "editing allowed": "편집 허용됨",
    "Open Submodule": "서브모듈 열기",
    "Update Submodule": "서브모듈 업데이트",
    "Updating submodule...": "서브모듈 업데이트 중...",
    "Repository Statistics": "저장소 통계",
    "Tag Details": "태그 정보",
    "New Issue": "새 이슈",
    "New Pull Request": "새 풀 리퀘스트",
    "Rescan": "다시 스캔",
    "Rescan repositories in source folder": "소스 폴더의 저장소 다시 스캔",
    "The directory is not under git source control": "디렉토리가 Git 소스 제어 하에 있지 않습니다",
    "Reveal Line in": "라인 표시:",
    "Run": "실행",
    "This custom  command was created in a newer version of Fork.\n Please check for updates in order to use it.": "이 사용자 정의 명령은 더 새로운 버전의 Fork에서 만들어졌습니다.\n 사용하려면 업데이트를 확인하세요.",
    "You should only run custom commands from trustworthy repositories. Do you really want to run it?": "신뢰할 수 있는 저장소의 사용자 정의 명령만 실행해야 합니다. 정말 실행하시겠습니까?",
    "Workspace": "워크스페이스",
    "Update": "업데이트",
    "Reset Branch": "브랜치 재설정",
    "Repository name:": "저장소 이름:",
    "Parent directory:": "상위 디렉토리:",
    "Move...": "이동...",
    "Move": "이동",
    "Untrack": "추적 해제",
    "Show output": "출력 표시",
    "Path to git.exe": "git.exe 경로",
    "Please select a valid git.exe file.": "유효한 git.exe 파일을 선택하세요.",
    "Unable to run selected Git executable.": "선택한 Git 실행 파일을 실행할 수 없습니다.",
    "Unable to open file picker. Please type the git.exe path manually.": "파일 선택기를 열 수 없습니다. git.exe 경로를 수동으로 입력하세요.",
    "[Submodule]": "[서브모듈]",
    "Show all": "모두 표시",
    "Select a detected Git executable or browse for another git.exe.": "감지된 Git 실행 파일을 선택하거나 다른 git.exe를 찾아보세요.",
    "Saved Git": "저장된 Git",
    "System PATH": "시스템 PATH",
    "PortableGit": "PortableGit",
    "Refreshing {0}": "{0} 새로고침 중",
    "git mm status refresh finished": "git mm 상태 새로고침 완료",
    "Scan": "스캔",
    "Status": "상태",
    "git mm Reference": "git mm 참조",
    "Show git mm reference": "git mm 참조 표시",
    "git mm reference document was not found.": "git mm 참조 문서를 찾을 수 없습니다.",
    "Select All": "모두 선택",
    "Performance Diagnostics": "성능 진단",
    "Recent Git and UI operation timings.": "최근 Git 및 UI 작업 시간.",
    "Recent samples": "최근 샘플",
    "This operation is taking longer than usual. Please wait.": "이 작업이 평소보다 오래 걸리고 있습니다. 기다려 주세요.",
    "Model:": "모델:",
    "Refresh models": "모델 새로고침",
    "Set service URL and API key first.": "먼저 서비스 URL과 API 키를 설정하세요.",
    "Refreshing models...": "모델 새로고침 중...",
    "Refresh AI models": "AI 모델 새로고침",
    "Retry count:": "재시도 횟수:",
    "Max timeout (seconds):": "최대 타임아웃 (초):",
    "{0} files": "{0}개 파일",
    "Reviewing files with {0}...": "{0}(으)로 파일 리뷰 중...",
    "Retry AI request ({0}/{1})...": "AI 요청 재시도 ({0}/{1})...",
    "{0} min": "{0}분",
    "{0} min {1}s": "{0}분 {1}초",
    "{0}s": "{0}초",
    "Preview replacement": "교체 미리보기",
    "No findings were reported for this file.": "이 파일에 대해 보고된 결과가 없습니다.",
    "No applicable suggestions for this file.": "이 파일에 적용 가능한 제안이 없습니다.",
    "Original": "원본",
    "Suggested": "제안",
    "Suggestion Preview": "제안 미리보기",
    "Retry AI Review": "AI 리뷰 재시도",
    "Retry AI Review for {0} files": "{0}개 파일 AI 리뷰 재시도",
    "Retrying AI review for {0} files...": "{0}개 파일 AI 리뷰 재시도 중...",
    "Retried AI review for {0} files.": "{0}개 파일 AI 리뷰 재시도 완료.",
    "Remote service returned an error response.": "원격 서비스에서 오류 응답을 반환했습니다.",
    "The recommended subject line should be {0} characters or less": "권장 제목은 {0}자 이하여야 합니다",
    "{0} - {1} Review": "{0} - {1} 리뷰",
    "{0} files - {1} Review": "{0}개 파일 - {1} 리뷰",
    "Skills": "스킬",
    "Send": "전송",
    "Select Skill File": "스킬 파일 선택",
    "Remove this skill": "이 스킬 제거",
    "Manual Input": "수동 입력",
    "Skill name:": "스킬 이름:",
    "SSH configuration: ": "SSH 설정: ",
    "Reveal Line in ": "다음 도구에서 라인 표시: ",
    "排队中...": "대기 중...",
    "🧑 我的需求": "🧑 내 요청",
    "🤖 AI 响应": "🤖 AI 응답",
    "⏳ 已加入队列 (队列中有 {0} 个待处理请求)": "⏳ 대기열에 추가됨 (대기열에 {0}개 요청 대기 중)",
    "正在请求 AI ({0})...": "AI 요청 중 ({0})...",
    "应用变更时出错: {0}": "변경사항 적용 중 오류: {0}",
    "📝 文件变更 ({0} 个文件)": "📝 파일 변경 ({0}개 파일)",
    "📄 新建: {0}": "📄 새로 만듦: {0}",
    "🗑️ 删除: {0}": "🗑️ 삭제: {0}",
    "✏️ 修改: {0}": "✏️ 수정: {0}",
    "🔄 开始处理下一个请求 (剩余 {0} 个)": "🔄 다음 요청 처리 시작 (남은 {0}개)",
    "Writing objects": "객체 쓰는 중",
    "Receiving objects": "객체 받는 중",
    "Resolving deltas": "델타 해결 중",
    "Updating files": "파일 업데이트 중",
    "# Stash uncommitted changes:": "# 미커밋 변경사항 스태시:",
    "# Synchronize '{0}' with '{1}':": "# '{0}'을(를) '{1}'과(와) 동기화:",
    "# Move '{0}' to '{1}':": "# '{0}'을(를) '{1}'(으)로 이동:",
    "# Update submodules:": "# 서브모듈 업데이트:",
    "fork: try to disable 'ignore whitespaces'": "fork: '공백 무시' 비활성화 시도",
    "fork: * ensure Fork has access to your organization": "fork: * Fork가 조직에 액세스할 수 있는지 확인",
    "fork: * ensure Fork uses correct account for the remote": "fork: * Fork가 리모트에 올바른 계정을 사용하는지 확인",
    "error: open('{0}'): Permission denied": "error: open('{0}'): 권한 거부됨",
    "fatal: cannot hash {0}": "fatal: {0}의 해시를 계산할 수 없음",
    "fatal: cannot hash": "fatal: 해시를 계산할 수 없음",
    "error: open({0}): Permission denied": "error: open({0}): 권한 거부됨",
    "New Notifications": "새 알림",
    "You've got {0} new notifications": "{0}개의 새 알림이 있습니다",
    "Select skill file": "스킬 파일 선택",
    "Text files (*.md;*.txt)": "텍스트 파일 (*.md;*.txt)",
    "Move the '{0}' branch HEAD to the selected revision": "'{0}' 브랜치 HEAD를 선택한 리비전으로 이동",
    "Pull '{0}' into '{1}'": "'{0}'을(를) '{1}'에 풀",
    "Run bash Script": "bash 스크립트 실행",
    "Switch to '{0}' branch": "'{0}' 브랜치로 전환",
    "The '{0}' directory is not a git repository": "'{0}' 디렉토리는 Git 저장소가 아닙니다",
    "The custom command has come from the '{0}' repository": "사용자 정의 명령은 '{0}' 저장소에서 가져왔습니다",
    "submodule update failed": "서브모듈 업데이트 실패",
    "Pruning LFS files...": "LFS 파일 정리 중...",
    "Message:\n": "메시지:\n",
    "Regenerating commit message with configured regex...": "구성된 정규식으로 커밋 메시지 재생성 중...",
    "Slug in '{0}'": "'{0}'의 Slug",
    "Remote url '{0}'": "리모트 URL '{0}'",
    # <<<INSERT>>>
}
